// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class OptionController
{
    private UnityEngine.RectTransform content;
    private UnityEngine.CanvasGroup uIMask;

    private void InitAutoBind()
    {
        content = Get<UnityEngine.RectTransform>("UIMask/Content");
        uIMask = Get<UnityEngine.CanvasGroup>("UIMask");

    }
}
