// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class MedicinalSolutionGameDataInfoUI
{
    private UnityEngine.UI.Image yanliao1;
    private TMPro.TextMeshProUGUI bindItem;
    private UnityEngine.UI.Image yanliao5;
    private TMPro.TextMeshProUGUI mlText;
    private UnityEngine.UI.Image ySIcon;

    private void InitAutoBind()
    {
        yanliao1 = Get<UnityEngine.UI.Image>("One/yanliao1");
        bindItem = Get<TMPro.TextMeshProUGUI>("One/+");
        yanliao5 = Get<UnityEngine.UI.Image>("One/yanliao5");
        mlText = Get<TMPro.TextMeshProUGUI>("Tow/mlText");
        ySIcon = Get<UnityEngine.UI.Image>("Three/YS_Icon");

    }
}
