// <auto-generated />
using UnityEngine;

public partial class MerchandiseSlot
{
    private TMPro.TextMeshProUGUI nameSlot;

    private void InitAutoBind()
    {
        nameSlot = Get<TMPro.TextMeshProUGUI>("NameSlot");

    }
}
