// <auto-generated />
using UnityEngine;

public partial class ClothingPage
{
    private UnityEngine.UI.ScrollRect scrollView;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("background/Main/Scroll View");

    }
}
