// <auto-generated />
using UnityEngine;

public partial class OnLineGameUI
{
    private CustomButton closeBtn;
    private SelectedButton fanInfoButton;
    private XFramework.FanPageUI fanPage;

    private void InitAutoBind()
    {
        closeBtn = Get<CustomButton>("UIMask/Page/CloseBtn");
        fanInfoButton = Get<SelectedButton>("UIMask/Page/Left/Info/FanInfoButton");
        fanPage = Get<XFramework.FanPageUI>("UIMask/Page/Right/Group/FanPage");

    }
}
