// <auto-generated />
using UnityEngine;

public partial class MerchandiseSelectedSlot
{
    private TMPro.TextMeshProUGUI nameSlot;
    private MerchandiseRuntimeSlot merchandiseRuntimeSlot;
    private LongPressButton subButton;

    private void InitAutoBind()
    {
        nameSlot = Get<TMPro.TextMeshProUGUI>("NameSlot");
        merchandiseRuntimeSlot = Get<MerchandiseRuntimeSlot>("SelectedImg/MerchandiseRuntimeSlot");
        subButton = Get<LongPressButton>("SubButton");

    }
}
