// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PuzzleUI
{
    private CustomButton btnTuichu;
    private UnityEngine.UI.Image originalImage;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/btn_tuichu");
        originalImage = Get<UnityEngine.UI.Image>("UIMask/background/back/OriginalFarme/RawImage/OriginalImage");

    }
}
