// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class TalkNameController
{
    private UnityEngine.RectTransform normal;
    private UnityEngine.RectTransform hCG;

    private void InitAutoBind()
    {
        normal = Get<UnityEngine.RectTransform>("Normal");
        hCG = Get<UnityEngine.RectTransform>("HCG");

    }
}
