// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class TalkContentController
{
    private UnityEngine.RectTransform normal;
    private UnityEngine.RectTransform hCG;
    private UnityEngine.Localization.Components.LocalizeStringEvent talkNormalContext;
    private UnityEngine.Localization.Components.LocalizeStringEvent talkHCGContext;

    private void InitAutoBind()
    {
        normal = Get<UnityEngine.RectTransform>("Normal");
        hCG = Get<UnityEngine.RectTransform>("HCG");
        talkNormalContext = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("Normal/TalkNormalContext");
        talkHCGContext = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("HCG/TalkHCGContext");

    }
}
