// <auto-generated />
using UnityEngine;

public partial class PopClothingSelectedUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private UnityEngine.Localization.Components.LocalizeStringEvent valueTex;
    private CustomButton closeButton;
    private CustomButton saveButton;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/background/Main/Scroll View");
        valueTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/background/TipsFarme/ValueTex");
        closeButton = Get<CustomButton>("UIMask/background/Top/CloseButton");
        saveButton = Get<CustomButton>("UIMask/background/TipsFarme/SaveButton");

    }
}
