// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class GameInfoUI
{
    private UnityEngine.UI.Image bj2;
    private UnityEngine.UI.Image gemIcon;

    private void InitAutoBind()
    {
        bj2 = Get<UnityEngine.UI.Image>("bujian2/bj2");
        gemIcon = Get<UnityEngine.UI.Image>("cankao/gemIcon");

    }
}
