// <auto-generated />
using UnityEngine;

public partial class BoothGameStartUI
{
    private TMPro.TextMeshProUGUI fenCount;
    private UnityEngine.UI.Image icon;
    private UnityEngine.Localization.Components.LocalizeStringEvent desc;
    private CustomButton optionClothingButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent clothingNameTip;
    private UnityEngine.UI.Button mask;

    private void InitAutoBind()
    {
        fenCount = Get<TMPro.TextMeshProUGUI>("UIMask/StartPage/FanInfoButton/fenCount");
        icon = Get<UnityEngine.UI.Image>("UIMask/StartPage/InfoFarme/Icon");
        desc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/StartPage/InfoFarme/Desc");
        optionClothingButton = Get<CustomButton>("UIMask/StartPage/InfoFarme/ClothingFarme/OptionClothingButton");
        clothingNameTip = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/StartPage/InfoFarme/ClothingFarme/ClothingNameTip");
        mask = Get<UnityEngine.UI.Button>("UIMask/StartPage/SurroundingFarme/Mask");

    }
}
