// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class BoothGameStartUI
{
    private TMPro.TextMeshProUGUI fenCount;
    private UnityEngine.UI.Image icon;
    private UnityEngine.Localization.Components.LocalizeStringEvent desc;
    private CustomButton optionClothingButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent clothingNameTip;
    private UnityEngine.UI.Button mask;
    private UnityEngine.RectTransform merchandiseView;
    private UnityEngine.UI.ScrollRect itemScrollRect;
    private UnityEngine.UI.Button addFactoryButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent totalValTex;
    private CustomButton autoAddButton;
    private CustomButton btnStart;
    private CustomButton btnSkip;

    private void InitAutoBind()
    {
        fenCount = Get<TMPro.TextMeshProUGUI>("UIMask/StartPage/FanInfoButton/fenCount");
        icon = Get<UnityEngine.UI.Image>("UIMask/StartPage/InfoFarme/Icon");
        desc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/StartPage/InfoFarme/Desc");
        optionClothingButton = Get<CustomButton>("UIMask/StartPage/InfoFarme/ClothingFarme/OptionClothingButton");
        clothingNameTip = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/StartPage/InfoFarme/ClothingFarme/ClothingNameTip");
        mask = Get<UnityEngine.UI.Button>("UIMask/StartPage/SurroundingFarme/Mask");
        merchandiseView = Get<UnityEngine.RectTransform>("UIMask/StartPage/SurroundingFarme/MerchandiseView");
        itemScrollRect = Get<UnityEngine.UI.ScrollRect>("UIMask/StartPage/SurroundingFarme/MerchandiseView/itemScrollRect");
        addFactoryButton = Get<UnityEngine.UI.Button>("UIMask/StartPage/SurroundingFarme/MerchandiseView/InfoFarme/AddFactoryButton");
        totalValTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/StartPage/SurroundingFarme/MerchandiseView/InfoFarme/TotalValTex");
        autoAddButton = Get<CustomButton>("UIMask/StartPage/SurroundingFarme/Top/AutoAddButton");
        btnStart = Get<CustomButton>("UIMask/btn_Start");
        btnSkip = Get<CustomButton>("UIMask/btn_Skip");

    }
}
