// <auto-generated />
using UnityEngine;

public partial class PopSelectedPictureUI
{
    private UnityEngine.UI.Button closeButton;
    private UnityEngine.UI.ScrollRect scrollView;
    private CustomButton confirmButton;

    private void InitAutoBind()
    {
        closeButton = Get<UnityEngine.UI.Button>("UIMask/Page/CloseButton");
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/Page/Panel/Scroll View");
        confirmButton = Get<CustomButton>("UIMask/Page/ConfirmButton");

    }
}
