// <auto-generated />
using UnityEngine;

public partial class ClawMachineGuideUI
{
    private UnityEngine.RectTransform itemContent;

    private void InitAutoBind()
    {
        itemContent = Get<UnityEngine.RectTransform>("UIMask/Panel/ItemPage/ItemContent");

    }
}
