// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class AccessoriesSlot
{
    private UnityEngine.Localization.Components.LocalizeStringEvent nameKey;
    private UnityEngine.UI.Image icon;
    private UnityEngine.UI.ScrollRect itemScroll;
    private CustomButton button;

    private void InitAutoBind()
    {
        nameKey = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("NameKey");
        icon = Get<UnityEngine.UI.Image>("Farme/AccerssoiesBack/icon");
        itemScroll = Get<UnityEngine.UI.ScrollRect>("Farme/ItemScroll");
        button = Get<CustomButton>("Button");

    }
}
