// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class TalkBackgroundController
{
    private UnityEngine.UI.Image talkNormalBackgroud;
    private UnityEngine.UI.Image talkHCGBackgroud;

    private void InitAutoBind()
    {
        talkNormalBackgroud = Get<UnityEngine.UI.Image>("TalkNormalBackgroud");
        talkHCGBackgroud = Get<UnityEngine.UI.Image>("TalkHCGBackgroud");

    }
}
