// <auto-generated />
using UnityEngine;

public partial class SettlementSlot
{
    private MerchandiseRuntimeSlot merchandiseRuntimeSlot;
    private UnityEngine.Localization.Components.LocalizeStringEvent itemNameStr;
    private UnityEngine.Localization.Components.LocalizeStringEvent coinVal;
    private UnityEngine.Localization.Components.LocalizeStringEvent countVal;

    private void InitAutoBind()
    {
        merchandiseRuntimeSlot = Get<MerchandiseRuntimeSlot>("MerchandiseRuntimeSlot");
        itemNameStr = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("ItemNameStr");
        coinVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("Image/CoinVal");
        countVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("Image_1/CountVal");

    }
}
