// <auto-generated />
using UnityEngine;

public partial class CommonTopUI
{
    private UnityEngine.Localization.Components.LocalizeStringEvent tileLabTex;
    private CustomButton closeButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent timeSlotVal;
    private TMPro.TextMeshProUGUI actionPointsVal;
    private TMPro.TextMeshProUGUI strengthValue;
    private UnityEngine.UI.Image timeSlotIcon;

    private void InitAutoBind()
    {
        tileLabTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("TitleFarme/TileLabTex");
        closeButton = Get<CustomButton>("CloseButton");
        timeSlotVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("PropFarme/TimeSlotLabel/TimeSlotVal");
        actionPointsVal = Get<TMPro.TextMeshProUGUI>("PropFarme/ActionPointsValueLabel/ActionPointsVal");
        strengthValue = Get<TMPro.TextMeshProUGUI>("PropFarme/StrengthLabel/StrengthValue");
        timeSlotIcon = Get<UnityEngine.UI.Image>("PropFarme/TimeSlotLabel/TimeSlotIcon");

    }
}
