// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PattentSlot
{
    private UnityEngine.UI.Image image;

    private void InitAutoBind()
    {
        image = GetComponent<UnityEngine.UI.Image>();

    }
}
