// <auto-generated />
using UnityEngine;

public partial class PopRewardPropertyUI
{
    private UnityEngine.RectTransform content;
    private CustomButton rewardBtn;

    private void InitAutoBind()
    {
        content = Get<UnityEngine.RectTransform>("Content");
        rewardBtn = Get<CustomButton>("RewardBtn");

    }
}
