// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbClothShopData _tbClothShopData;

        public TbClothShopData TbClothShopData
        {
            get
            {
                return LoadTable(
                    ref _tbClothShopData,
                    AssetKeys.TbclothshopdataPath,
                    json => new TbClothShopData(json)
                );
            }
        }

        private TbDialogueData _tbDialogueData;

        public TbDialogueData TbDialogueData
        {
            get
            {
                return LoadTable(
                    ref _tbDialogueData,
                    AssetKeys.TbdialoguedataPath,
                    json => new TbDialogueData(json)
                );
            }
        }

        private TbNpcData _tbNpcData;

        public TbNpcData TbNpcData
        {
            get
            {
                return LoadTable(
                    ref _tbNpcData,
                    AssetKeys.TbnpcdataPath,
                    json => new TbNpcData(json)
                );
            }
        }

        private TbPropertyData _tbPropertyData;

        public TbPropertyData TbPropertyData
        {
            get
            {
                return LoadTable(
                    ref _tbPropertyData,
                    AssetKeys.TbpropertydataPath,
                    json => new TbPropertyData(json)
                );
            }
        }

        private TbUIPageData _tbUIPageData;

        public TbUIPageData TbUIPageData
        {
            get
            {
                return LoadTable(
                    ref _tbUIPageData,
                    AssetKeys.TbuipagedataPath,
                    json => new TbUIPageData(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbClothShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbclothshopdataPath);
            _tbDialogueData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdialoguedataPath);
            _tbNpcData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbnpcdataPath);
            _tbPropertyData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbpropertydataPath);
            _tbUIPageData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbuipagedataPath);
        }
    }
}
