// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbDialogueData _tbDialogueData;

        public TbDialogueData TbDialogueData
        {
            get
            {
                return LoadTable(
                    ref _tbDialogueData,
                    AssetKeys.TbdialoguedataPath,
                    json => new TbDialogueData(json)
                );
            }
        }

        private TbNpcData _tbNpcData;

        public TbNpcData TbNpcData
        {
            get
            {
                return LoadTable(
                    ref _tbNpcData,
                    AssetKeys.TbnpcdataPath,
                    json => new TbNpcData(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbDialogueData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdialoguedataPath);
            _tbNpcData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbnpcdataPath);
        }
    }
}
