// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbCharacterData _tbCharacterData;

        public TbCharacterData TbCharacterData
        {
            get
            {
                return LoadTable(
                    ref _tbCharacterData,
                    AssetKeys.TbcharacterdataPath,
                    json => new TbCharacterData(json)
                );
            }
        }

        private TbClothShopData _tbClothShopData;

        public TbClothShopData TbClothShopData
        {
            get
            {
                return LoadTable(
                    ref _tbClothShopData,
                    AssetKeys.TbclothshopdataPath,
                    json => new TbClothShopData(json)
                );
            }
        }

        private TbConsumablesItemData _tbConsumablesItemData;

        public TbConsumablesItemData TbConsumablesItemData
        {
            get
            {
                return LoadTable(
                    ref _tbConsumablesItemData,
                    AssetKeys.TbconsumablesitemdataPath,
                    json => new TbConsumablesItemData(json)
                );
            }
        }

        private TbDialogueData _tbDialogueData;

        public TbDialogueData TbDialogueData
        {
            get
            {
                return LoadTable(
                    ref _tbDialogueData,
                    AssetKeys.TbdialoguedataPath,
                    json => new TbDialogueData(json)
                );
            }
        }

        private TbDollCatalogData _tbDollCatalogData;

        public TbDollCatalogData TbDollCatalogData
        {
            get
            {
                return LoadTable(
                    ref _tbDollCatalogData,
                    AssetKeys.TbdollcatalogdataPath,
                    json => new TbDollCatalogData(json)
                );
            }
        }

        private TbFishShopData _tbFishShopData;

        public TbFishShopData TbFishShopData
        {
            get
            {
                return LoadTable(
                    ref _tbFishShopData,
                    AssetKeys.TbfishshopdataPath,
                    json => new TbFishShopData(json)
                );
            }
        }

        private TbFruitShopData _tbFruitShopData;

        public TbFruitShopData TbFruitShopData
        {
            get
            {
                return LoadTable(
                    ref _tbFruitShopData,
                    AssetKeys.TbfruitshopdataPath,
                    json => new TbFruitShopData(json)
                );
            }
        }

        private TbGameSceneData _tbGameSceneData;

        public TbGameSceneData TbGameSceneData
        {
            get
            {
                return LoadTable(
                    ref _tbGameSceneData,
                    AssetKeys.TbgamescenedataPath,
                    json => new TbGameSceneData(json)
                );
            }
        }

        private TbItemData _tbItemData;

        public TbItemData TbItemData
        {
            get
            {
                return LoadTable(
                    ref _tbItemData,
                    AssetKeys.TbitemdataPath,
                    json => new TbItemData(json)
                );
            }
        }

        private TbNpcData _tbNpcData;

        public TbNpcData TbNpcData
        {
            get
            {
                return LoadTable(
                    ref _tbNpcData,
                    AssetKeys.TbnpcdataPath,
                    json => new TbNpcData(json)
                );
            }
        }

        private TbNpcSpawnGroupData _tbNpcSpawnGroupData;

        public TbNpcSpawnGroupData TbNpcSpawnGroupData
        {
            get
            {
                return LoadTable(
                    ref _tbNpcSpawnGroupData,
                    AssetKeys.TbnpcspawngroupdataPath,
                    json => new TbNpcSpawnGroupData(json)
                );
            }
        }

        private TbNpcSpawnRuleData _tbNpcSpawnRuleData;

        public TbNpcSpawnRuleData TbNpcSpawnRuleData
        {
            get
            {
                return LoadTable(
                    ref _tbNpcSpawnRuleData,
                    AssetKeys.TbnpcspawnruledataPath,
                    json => new TbNpcSpawnRuleData(json)
                );
            }
        }

        private TbPropertyData _tbPropertyData;

        public TbPropertyData TbPropertyData
        {
            get
            {
                return LoadTable(
                    ref _tbPropertyData,
                    AssetKeys.TbpropertydataPath,
                    json => new TbPropertyData(json)
                );
            }
        }

        private TbSexToShopData _tbSexToShopData;

        public TbSexToShopData TbSexToShopData
        {
            get
            {
                return LoadTable(
                    ref _tbSexToShopData,
                    AssetKeys.TbsextoshopdataPath,
                    json => new TbSexToShopData(json)
                );
            }
        }

        private TbSuperMarketShopData _tbSuperMarketShopData;

        public TbSuperMarketShopData TbSuperMarketShopData
        {
            get
            {
                return LoadTable(
                    ref _tbSuperMarketShopData,
                    AssetKeys.TbsupermarketshopdataPath,
                    json => new TbSuperMarketShopData(json)
                );
            }
        }

        private TbUIPageData _tbUIPageData;

        public TbUIPageData TbUIPageData
        {
            get
            {
                return LoadTable(
                    ref _tbUIPageData,
                    AssetKeys.TbuipagedataPath,
                    json => new TbUIPageData(json)
                );
            }
        }

        private TbUnlockConditionsData _tbUnlockConditionsData;

        public TbUnlockConditionsData TbUnlockConditionsData
        {
            get
            {
                return LoadTable(
                    ref _tbUnlockConditionsData,
                    AssetKeys.TbunlockconditionsdataPath,
                    json => new TbUnlockConditionsData(json)
                );
            }
        }

        private TbWordMapSceneData _tbWordMapSceneData;

        public TbWordMapSceneData TbWordMapSceneData
        {
            get
            {
                return LoadTable(
                    ref _tbWordMapSceneData,
                    AssetKeys.TbwordmapscenedataPath,
                    json => new TbWordMapSceneData(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbCharacterData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbcharacterdataPath);
            _tbClothShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbclothshopdataPath);
            _tbConsumablesItemData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbconsumablesitemdataPath);
            _tbDialogueData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdialoguedataPath);
            _tbDollCatalogData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdollcatalogdataPath);
            _tbFishShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbfishshopdataPath);
            _tbFruitShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbfruitshopdataPath);
            _tbGameSceneData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbgamescenedataPath);
            _tbItemData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbitemdataPath);
            _tbNpcData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbnpcdataPath);
            _tbNpcSpawnGroupData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbnpcspawngroupdataPath);
            _tbNpcSpawnRuleData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbnpcspawnruledataPath);
            _tbPropertyData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbpropertydataPath);
            _tbSexToShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbsextoshopdataPath);
            _tbSuperMarketShopData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbsupermarketshopdataPath);
            _tbUIPageData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbuipagedataPath);
            _tbUnlockConditionsData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbunlockconditionsdataPath);
            _tbWordMapSceneData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbwordmapscenedataPath);
        }
    }
}
