// <auto-generated />
using UnityEngine;

public partial class PopUnlockDollWindowsUI
{
    private UnityEngine.Localization.Components.LocalizeStringEvent dollNameKey;
    private UnityEngine.UI.Image dollIcon;
    private UnityEngine.Localization.Components.LocalizeStringEvent qualityTex;
    private UnityEngine.Localization.Components.LocalizeStringEvent descString;
    private UnityEngine.Localization.Components.LocalizeStringEvent useTex;
    private CustomButton image;

    private void InitAutoBind()
    {
        dollNameKey = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/TweenerRoot/DollNameKey");
        dollIcon = Get<UnityEngine.UI.Image>("UIMask/TweenerRoot/Image/dollIcon");
        qualityTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/TweenerRoot/QualityTex");
        descString = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/TweenerRoot/DescString");
        useTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/TweenerRoot/UseTex");
        image = Get<CustomButton>("UIMask/TweenerRoot/CloseButton");

    }
}
