// <auto-generated />
using UnityEngine;

public partial class PopRewardUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private CustomButton button;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/Background/Scroll View");
        button = Get<CustomButton>("UIMask/Background/Button");

    }
}
