// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class SewingMachineUI
{
    private CustomButton btnTuichu;
    private UnityEngine.RectTransform mouseParent;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/Top/btn_tuichu");
        mouseParent = Get<UnityEngine.RectTransform>("UIMask/MouseParent");

    }
}
