// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class SewingMachineUI
{
    private CustomButton btnTuichu;
    private SweingMachinePanel sewingMachinePanel;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/Top/btn_tuichu");
        sewingMachinePanel = Get<SweingMachinePanel>("UIMask/SewingMachinePanel");

    }
}
