// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CharacterClothingSlot
{
    private List<BodyAccessoriesSlot> bodyAccessoriesList;

    private void InitAutoBind()
    {
        bodyAccessoriesList = Get<Transform>("BodyAccessoriesList").GetComponentsInChildren<BodyAccessoriesSlot>(true).Where(item => item.transform != Get<Transform>("BodyAccessoriesList")).ToList();

    }
}
