// <auto-generated />
using UnityEngine;

public partial class BagController
{
    private UnityEngine.UI.Image icon;
    private UnityEngine.Localization.Components.LocalizeStringEvent nameStringTex;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("icon");
        nameStringTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("NameStringTex");

    }
}
