// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class DramaRuntimeUI
{
    private TalkActionController talkActionController;

    private void InitAutoBind()
    {
        talkActionController = Get<TalkActionController>("Page/TalkActionController");

    }
}
