// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PcbItemSlot
{
    private UnityEngine.UI.Image image;
    private UnityEngine.RectTransform rotationFarme;
    private UnityEngine.EventSystems.EventTrigger rotation;

    private void InitAutoBind()
    {
        image = GetComponent<UnityEngine.UI.Image>();
        rotationFarme = Get<UnityEngine.RectTransform>("RotationFarme");
        rotation = Get<UnityEngine.EventSystems.EventTrigger>("Rotation");

    }
}
