// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ActorController
{
    private UnityEngine.RectTransform directionLeft;
    private UnityEngine.RectTransform directionCenter;
    private UnityEngine.RectTransform directionRight;

    private void InitAutoBind()
    {
        directionLeft = Get<UnityEngine.RectTransform>("Direction_Left");
        directionCenter = Get<UnityEngine.RectTransform>("Direction_Center");
        directionRight = Get<UnityEngine.RectTransform>("Direction_Right");

    }
}
