// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class UpperBodyUI
{
    private CustomButton btnTuichu;
    private UnityEngine.RectTransform background;
    private CharacterClothingSlot characterClothingSlot;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/btn_tuichu");
        background = Get<UnityEngine.RectTransform>("UIMask/Right/background");
        characterClothingSlot = Get<CharacterClothingSlot>("UIMask/Left/CharacterClothingSlot");

    }
}
