// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class UpperBodyUI
{
    private CustomButton btnTuichu;
    private UnityEngine.RectTransform slotContent;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/btn_tuichu");
        slotContent = Get<UnityEngine.RectTransform>("UIMask/Right/SlotContent");

    }
}
