// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class EditorButtonGroups
{
    private CustomButton rotationButton;
    private CustomButton deleteButton;

    private void InitAutoBind()
    {
        rotationButton = Get<CustomButton>("RotationButton");
        deleteButton = Get<CustomButton>("DeleteButton");

    }
}
