// <auto-generated />
using UnityEngine;

public partial class GarmentMakingUI
{
    private UnityEngine.Localization.Components.LocalizeStringEvent tileLabTex;
    private CommonTopUI commonTopUI;
    private UnityEngine.UI.ScrollRect scrollView;

    private void InitAutoBind()
    {
        tileLabTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/CommonTopUI/TitleFarme/TileLabTex");
        commonTopUI = Get<CommonTopUI>("UIMask/CommonTopUI");
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/bakcground/Right/Background/Scroll View");

    }
}
