// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class GarmentMakingUI
{
    private UnityEngine.Localization.Components.LocalizeStringEvent tileLabTex;
    private CommonTopUI commonTopUI;
    private UnityEngine.UI.ScrollRect scrollView;
    private CustomButton starButton;
    private ClothingFittingUI clothingFittingUI;
    private UnityEngine.RectTransform viewPanel;
    private UnityEngine.CanvasGroup nodeFace;
    private UnityEngine.CanvasGroup characterNormal;
    private CustomButton quitButton;
    private ClothingItemInfo clothingItemInfo;

    private void InitAutoBind()
    {
        tileLabTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/CommonTopUI/TitleFarme/TileLabTex");
        commonTopUI = Get<CommonTopUI>("UIMask/CommonTopUI");
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/bakcground/Right/ViewPanel/Background/Scroll View");
        starButton = Get<CustomButton>("UIMask/bakcground/Right/ViewPanel/StarButton");
        clothingFittingUI = Get<ClothingFittingUI>("UIMask/bakcground/Right/ClothingFittingUI");
        viewPanel = Get<UnityEngine.RectTransform>("UIMask/bakcground/Right/ViewPanel");
        nodeFace = Get<UnityEngine.CanvasGroup>("UIMask/bakcground/Left/NodeFace");
        characterNormal = Get<UnityEngine.CanvasGroup>("UIMask/bakcground/Left/CharacterNormal");
        quitButton = Get<CustomButton>("UIMask/QuitButton");
        clothingItemInfo = Get<ClothingItemInfo>("UIMask/bakcground/Right/ClothingItemInfo");

    }
}
