// <auto-generated />
using UnityEngine;

public partial class PopMerchandiseSelectedUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private CustomButton closeButton;
    private CustomButton saveButton;
    private CustomButton autoAddButton;
    private CustomButton addButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent totalValTex;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/background/Main/Scroll View");
        closeButton = Get<CustomButton>("UIMask/background/Top/CloseButton");
        saveButton = Get<CustomButton>("UIMask/background/TipsFarme/SaveButton");
        autoAddButton = Get<CustomButton>("UIMask/background/TipsFarme/LayoutGroup/AutoAddButton");
        addButton = Get<CustomButton>("UIMask/background/TipsFarme/LayoutGroup/AddButton");
        totalValTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/background/TipsFarme/LayoutGroup/TotalValTex");

    }
}
