// <auto-generated />
using UnityEngine;

public partial class PopMerchandiseSelectedUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private CustomButton closeButton;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/background/Main/Scroll View");
        closeButton = Get<CustomButton>("UIMask/background/Top/CloseButton");

    }
}
