// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ClothingItemInfo
{
    private TMPro.TextMeshProUGUI minGameNameStr;
    private TMPro.TextMeshProUGUI minGameDescStr;
    private UnityEngine.UI.ScrollRect itemScroll;
    private UnityEngine.UI.Button indexUpButton;
    private TMPro.TextMeshProUGUI indexTex;
    private UnityEngine.UI.Button indexDownButton;
    private UnityEngine.UI.Button starButton;

    private void InitAutoBind()
    {
        minGameNameStr = Get<TMPro.TextMeshProUGUI>("Content/Top/minGameNameStr");
        minGameDescStr = Get<TMPro.TextMeshProUGUI>("Content/Top/minGameDescStr");
        itemScroll = Get<UnityEngine.UI.ScrollRect>("Content/Down/ItemScroll");
        indexUpButton = Get<UnityEngine.UI.Button>("NoFarme/IndexUpButton");
        indexTex = Get<TMPro.TextMeshProUGUI>("NoFarme/IndexTex");
        indexDownButton = Get<UnityEngine.UI.Button>("NoFarme/indexDownButton");
        starButton = Get<UnityEngine.UI.Button>("Content/StarButton");

    }
}
