// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ScreenActionController
{
    private UnityEngine.UI.Image fadeController;

    private void InitAutoBind()
    {
        fadeController = Get<UnityEngine.UI.Image>("FadeController");

    }
}
