

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.item
{

public partial class TbReward
{
    private readonly System.Collections.Generic.Dictionary<int, item.Reward> _dataMap;
    private readonly System.Collections.Generic.List<item.Reward> _dataList;
    
    public TbReward(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Reward>(_buf.Count);
        _dataList = new System.Collections.Generic.List<item.Reward>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            item.Reward _v;
            _v = global::cfg.item.Reward.DeserializeReward(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, item.Reward> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<item.Reward> DataList => _dataList;

    public item.Reward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public item.Reward Get(int key) => _dataMap[key];
    public item.Reward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

