// <auto-generated />
using UnityEngine;

public partial class ExhibitionCharacterUI
{
    private UnityEngine.CanvasGroup exhibitionCharacterUI;
    private UnityEngine.EventSystems.EventTrigger icon;
    private CustomButton photograph;
    private UnityEngine.UI.Slider dwellSlider;
    private UnityEngine.RectTransform infoUI;
    private UnityEngine.CanvasGroup checkFamre;
    private UnityEngine.RectTransform processIcon;
    private UnityEngine.RectTransform successIcon;
    private UnityEngine.RectTransform failIcon;
    private UnityEngine.RectTransform exitText;
    private UnityEngine.RectTransform completePhotograph;
    private UnityEngine.CanvasGroup photographFarme;

    private void InitAutoBind()
    {
        exhibitionCharacterUI = GetComponent<UnityEngine.CanvasGroup>();
        icon = Get<UnityEngine.EventSystems.EventTrigger>("icon");
        photograph = Get<CustomButton>("InfoUI/Top/Photograph");
        dwellSlider = Get<UnityEngine.UI.Slider>("InfoUI/Right/DwellSlider");
        infoUI = Get<UnityEngine.RectTransform>("InfoUI");
        checkFamre = Get<UnityEngine.CanvasGroup>("InfoUI/CheckFamre");
        processIcon = Get<UnityEngine.RectTransform>("InfoUI/CheckFamre/ProcessIcon");
        successIcon = Get<UnityEngine.RectTransform>("InfoUI/CheckFamre/SuccessIcon");
        failIcon = Get<UnityEngine.RectTransform>("InfoUI/CheckFamre/FailIcon");
        exitText = Get<UnityEngine.RectTransform>("ExitText");
        completePhotograph = Get<UnityEngine.RectTransform>("InfoUI/Top/CompletePhotograph");
        photographFarme = Get<UnityEngine.CanvasGroup>("PhotographFarme");

    }
}
