// <auto-generated />
using UnityEngine;

public partial class ExhibitionCharacterUI
{
    private UnityEngine.CanvasGroup exhibitionCharacterUI;
    private UnityEngine.UI.Image icon;
    private UnityEngine.RectTransform photograph;
    private UnityEngine.UI.Slider dwellSlider;
    private UnityEngine.RectTransform infoUI;

    private void InitAutoBind()
    {
        exhibitionCharacterUI = GetComponent<UnityEngine.CanvasGroup>();
        icon = Get<UnityEngine.UI.Image>("icon");
        photograph = Get<UnityEngine.RectTransform>("InfoUI/Top/Photograph");
        dwellSlider = Get<UnityEngine.UI.Slider>("InfoUI/Right/DwellSlider");
        infoUI = Get<UnityEngine.RectTransform>("InfoUI");

    }
}
