// <auto-generated />
using UnityEngine;

public partial class FlySlot
{
    private UnityEngine.UI.Image flySlot;
    private UnityEngine.Localization.Components.LocalizeStringEvent nameString;

    private void InitAutoBind()
    {
        flySlot = GetComponent<UnityEngine.UI.Image>();
        nameString = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("NameString");

    }
}
