// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ClothingFittingUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private TMPro.TextMeshProUGUI indexTex;
    private UnityEngine.UI.Button indexDownButton;
    private UnityEngine.UI.Button indexUpButton;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("Scroll View");
        indexTex = Get<TMPro.TextMeshProUGUI>("NoFarme/IndexTex");
        indexDownButton = Get<UnityEngine.UI.Button>("NoFarme/indexDownButton");
        indexUpButton = Get<UnityEngine.UI.Button>("NoFarme/IndexUpButton");

    }
}
