// <auto-generated />
using UnityEngine;

public partial class ClothingFittingUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private TMPro.TextMeshProUGUI indexTex;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("Scroll View");
        indexTex = Get<TMPro.TextMeshProUGUI>("NoFarme/IndexTex");

    }
}
