// <auto-generated />
using UnityEngine;

public partial class RewardSlotItem
{
    private UnityEngine.UI.Image icon;
    private UnityEngine.Localization.Components.LocalizeStringEvent itemName;
    private TMPro.TextMeshProUGUI itemCount;
    private UnityEngine.Localization.Components.LocalizeStringEvent itemDesc;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("ItemFarme/icon");
        itemName = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("ItemName");
        itemCount = Get<TMPro.TextMeshProUGUI>("ItemCount");
        itemDesc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("ItemDesc");

    }
}
