// <auto-generated />
using UnityEngine;

public partial class ClothingSlot
{
    private UnityEngine.UI.Image icon;
    private UnityEngine.Localization.Components.LocalizeStringEvent nameString;
    private SelectedButton selectedButton;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("icon");
        nameString = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("NameString");
        selectedButton = Get<SelectedButton>("SelectedButton");

    }
}
