// <auto-generated />
using UnityEngine;

public partial class PackController
{
    private UnityEngine.UI.Image bagType01;
    private UnityEngine.UI.Image bagType02;

    private void InitAutoBind()
    {
        bagType01 = Get<UnityEngine.UI.Image>("bagType_01");
        bagType02 = Get<UnityEngine.UI.Image>("bagType_02");

    }
}
