// <auto-generated />
using UnityEngine;

public partial class PackController
{
    private UnityEngine.UI.Image bag;

    private void InitAutoBind()
    {
        bag = Get<UnityEngine.UI.Image>("bag");

    }
}
