
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterPropData : Luban.BeanBase
{
    public CharacterPropData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Property = (CharacterPropType)(int)_obj.GetValue("Property");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        Remark = (string)_obj.GetValue("Remark");
        DeftualNumber = (int)_obj.GetValue("DeftualNumber");
    }

    public static CharacterPropData DeserializeCharacterPropData(JToken _buf)
    {
        return new CharacterPropData(_buf);
    }

    /// <summary>
    /// 属性
    /// </summary>
    public readonly CharacterPropType Property;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly TbLocalzationKeyData Name;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 默认值
    /// </summary>
    public readonly int DeftualNumber;


    public const int __ID__ = 1638122454;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Property:" + Property + ","
        + "Name:" + Name + ","
        + "Remark:" + Remark + ","
        + "DeftualNumber:" + DeftualNumber + ","
        + "}";
    }
}
}

