
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ClothingPaintTubeMoldType
    {
        /// <summary>
        /// 模具类型A
        /// </summary>
        A = 0,
        /// <summary>
        /// 模具类型B
        /// </summary>
        B = 1,
        /// <summary>
        /// 模具类型C
        /// </summary>
        C = 2,
        /// <summary>
        /// 模具类型D
        /// </summary>
        D = 3,
    }

} 

