
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ClothShopData : Luban.BeanBase
{
    public ClothShopData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        ItemNumber = (int)_obj.GetValue("ItemNumber");
        Price = (int)_obj.GetValue("Price");
        UpdateMode = (ShopUpdateType)(int)_obj.GetValue("UpdateMode");
        BuyLimit = (int)_obj.GetValue("BuyLimit");
    }

    public static ClothShopData DeserializeClothShopData(JToken _buf)
    {
        return new ClothShopData(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 物品数量
    /// </summary>
    public readonly int ItemNumber;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 刷新模式
    /// </summary>
    public readonly ShopUpdateType UpdateMode;
    /// <summary>
    /// 购买上限
    /// </summary>
    public readonly int BuyLimit;


    public const int __ID__ = 381193178;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "ItemNumber:" + ItemNumber + ","
        + "Price:" + Price + ","
        + "UpdateMode:" + UpdateMode + ","
        + "BuyLimit:" + BuyLimit + ","
        + "}";
    }
}
}

