
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum DialogueEndActionType
    {
        /// <summary>
        /// 无操作
        /// </summary>
        Node = 0,
        /// <summary>
        /// 功能面板
        /// </summary>
        FunctionGroup = 1,
    }

} 

