
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum DialogueType
    {
        /// <summary>
        /// 普通角色对话
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 旁白
        /// </summary>
        Narration = 2,
        /// <summary>
        /// 内心独白
        /// </summary>
        InnerMonologue = 3,
        /// <summary>
        ///  系统提示
        /// </summary>
        SystemNotification = 4,
        /// <summary>
        /// 过场动画对话
        /// </summary>
        Cutscene = 5,
        /// <summary>
        /// 剧情推进对话
        /// </summary>
        StoryDialogue = 6,
    }

} 

