
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum DlgPriorityType
    {
        /// <summary>
        /// 日常对话(点击角色直接触发)
        /// </summary>
        DailyConversation = 1,
        /// <summary>
        /// 支线对话（点击角色直接触发）
        /// </summary>
        SideQuestDialogue = 2,
    }

} 

