
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DramaData : Luban.BeanBase
{
    public DramaData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        DramaScriptsPath = (string)_obj.GetValue("DramaScriptsPath");
    }

    public static DramaData DeserializeDramaData(JToken _buf)
    {
        return new DramaData(_buf);
    }

    /// <summary>
    /// 剧情ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 生成的剧情文本路径
    /// </summary>
    public readonly string DramaScriptsPath;


    public const int __ID__ = 1864856209;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "DramaScriptsPath:" + DramaScriptsPath + ","
        + "}";
    }
}
}

