
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        C = 1,
        /// <summary>
        /// 高级
        /// </summary>
        B = 2,
        /// <summary>
        /// 稀有
        /// </summary>
        A = 3,
        /// <summary>
        /// 神器
        /// </summary>
        S = 4,
        /// <summary>
        /// 史诗
        /// </summary>
        SSR = 5,
    }

} 

