
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum LlustrationDirection
    {
        /// <summary>
        /// 适配左
        /// </summary>
        Left = 1,
        /// <summary>
        /// 适配中
        /// </summary>
        Crent = 2,
        /// <summary>
        /// 适配右
        /// </summary>
        Right = 3,
    }

} 

