
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum MiniGameResult
    {
        /// <summary>
        /// 不分胜负 / 不限胜负
        /// </summary>
        None = 0,
        /// <summary>
        /// 本局胜利
        /// </summary>
        Win = 1,
        /// <summary>
        /// 本局失败
        /// </summary>
        Lose = 2,
    }

} 

