
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum MiniGameType
    {
        /// <summary>
        /// 未设置
        /// </summary>
        None = 0,
        /// <summary>
        /// 赌场：倍率冲刺，见好就收
        /// </summary>
        CrashSprint = 1,
        /// <summary>
        /// 赌场：开瓶避毒
        /// </summary>
        WitchPotion = 2,
        /// <summary>
        /// 钓鱼：遛鱼成功算胜
        /// </summary>
        Fishing = 3,
        /// <summary>
        /// 厨房：做菜成功算胜
        /// </summary>
        Cooking = 4,
        /// <summary>
        /// 服装：喷漆上色，通关算胜
        /// </summary>
        SprayPaint = 5,
        /// <summary>
        /// 服装：刺绣填色，通关算胜
        /// </summary>
        Embroidery = 6,
        /// <summary>
        /// 超市帮忙摆货，摆满算胜
        /// </summary>
        ShopHelp = 7,
        /// <summary>
        /// 加工厂下压音游，有产出算胜
        /// </summary>
        FactoryProcess = 8,
        /// <summary>
        /// 加工厂物料制作，不分胜负
        /// </summary>
        FactoryMold = 9,
        /// <summary>
        /// 摄影棚对焦，达标算胜
        /// </summary>
        PhotoStudio = 10,
    }

} 

