
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class PcbSlotData : Luban.BeanBase
{
    public PcbSlotData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        MinIconName = (string)_obj.GetValue("minIconName");
        MaxIconName = (string)_obj.GetValue("maxIconName");
    }

    public static PcbSlotData DeserializePcbSlotData(JToken _buf)
    {
        return new PcbSlotData(_buf);
    }

    /// <summary>
    /// 唯一标识ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 略缩图
    /// </summary>
    public readonly string MinIconName;
    /// <summary>
    /// 原始图
    /// </summary>
    public readonly string MaxIconName;


    public const int __ID__ = -2061460329;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "minIconName:" + MinIconName + ","
        + "maxIconName:" + MaxIconName + ","
        + "}";
    }
}
}

