
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum PermanentSceneType
    {
        /// <summary>
        /// 默认就存在的场景
        /// </summary>
        Permanent = 0,
        /// <summary>
        /// 根据条件出现的场景
        /// </summary>
        Special = 1,
    }

} 

