
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum PrevSpriteHandleType
    {
        /// <summary>
        /// 删除
        /// </summary>
        DEL = 1,
        /// <summary>
        /// 黑色遮罩
        /// </summary>
        MASK = 2,
        /// <summary>
        /// 同时显示
        /// </summary>
        OVERRIDE = 3,
    }

} 

