
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum QuestRewardType
    {
        /// <summary>
        /// 未设置
        /// </summary>
        None = 0,
        /// <summary>
        /// Item:道具ID[:数量]，数量默认 1
        /// </summary>
        Item = 1,
        /// <summary>
        /// Coin:数值
        /// </summary>
        Coin = 2,
        /// <summary>
        /// GameCoin:数值
        /// </summary>
        GameCoin = 3,
        /// <summary>
        /// Affection:NPC ID:数值
        /// </summary>
        Affection = 4,
    }

} 

