
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum QuestTriggerType
    {
        /// <summary>
        /// 不配触发，只看领取条件
        /// </summary>
        None = 0,
        /// <summary>
        /// Auto，读档或任意事件后立即尝试领取
        /// </summary>
        Auto = 1,
        /// <summary>
        /// EnterZone:场景ID
        /// </summary>
        EnterZone = 2,
        /// <summary>
        /// ExitZone:场景ID
        /// </summary>
        ExitZone = 3,
        /// <summary>
        /// EnterZoneStay:场景ID:停留秒数
        /// </summary>
        EnterZoneStay = 4,
        /// <summary>
        /// ClickNpc:NPC ID
        /// </summary>
        ClickNpc = 5,
        /// <summary>
        /// DialogNpc:NPC ID
        /// </summary>
        DialogNpc = 6,
        /// <summary>
        /// MiniGameEnd:小游戏ID
        /// </summary>
        MiniGameEnd = 7,
        /// <summary>
        /// MiniGameResult:小游戏ID:结果 1胜/2负
        /// </summary>
        MiniGameResult = 8,
        /// <summary>
        /// RandomChance:千分比
        /// </summary>
        RandomChance = 9,
        /// <summary>
        /// PlotEnd:剧情ID，剧情完成记录未实现，永不触发
        /// </summary>
        PlotEnd = 10,
    }

} 

