
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class RacingTrackData : Luban.BeanBase
{
    public RacingTrackData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        NameKey = (string)_obj.GetValue("NameKey");
        RoutePath = (string)_obj.GetValue("RoutePath");
        LapCount = (int)_obj.GetValue("LapCount");
        CarSpeed = (float)_obj.GetValue("CarSpeed");
        ViewDistance = (float)_obj.GetValue("ViewDistance");
        FullDeflectRadius = (float)_obj.GetValue("FullDeflectRadius");
        TimeLimitSec = (int)_obj.GetValue("TimeLimitSec");
        UnlockConditionID = (long)_obj.GetValue("UnlockConditionID");
    }

    public static RacingTrackData DeserializeRacingTrackData(JToken _buf)
    {
        return new RacingTrackData(_buf);
    }

    /// <summary>
    /// 赛道ID(表主键)
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 赛道名多语言Key(如 CIRCUIT No.1)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 赛道线路资产Addressable Key(RacingTrackRoute)
    /// </summary>
    public readonly string RoutePath;
    /// <summary>
    /// 总圈数
    /// </summary>
    public readonly int LapCount;
    /// <summary>
    /// 车辆基准速度(米/秒)
    /// </summary>
    public readonly float CarSpeed;
    /// <summary>
    /// 最远可视距离(米),决定一眼能看到前方多少赛道
    /// </summary>
    public readonly float ViewDistance;
    /// <summary>
    /// 满偏移弯道半径(米),越小越容易把画面推满
    /// </summary>
    public readonly float FullDeflectRadius;
    /// <summary>
    /// 限时(秒),0为不限时
    /// </summary>
    public readonly int TimeLimitSec;
    /// <summary>
    /// 解锁条件ID(0为默认解锁)
    /// </summary>
    public readonly long UnlockConditionID;


    public const int __ID__ = -1466568761;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NameKey:" + NameKey + ","
        + "RoutePath:" + RoutePath + ","
        + "LapCount:" + LapCount + ","
        + "CarSpeed:" + CarSpeed + ","
        + "ViewDistance:" + ViewDistance + ","
        + "FullDeflectRadius:" + FullDeflectRadius + ","
        + "TimeLimitSec:" + TimeLimitSec + ","
        + "UnlockConditionID:" + UnlockConditionID + ","
        + "}";
    }
}
}

