
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum RefreshType
    {
        /// <summary>
        /// 时间段
        /// </summary>
        TimeSlot = 1,
        /// <summary>
        /// 每天
        /// </summary>
        Day = 2,
        /// <summary>
        /// 每次
        /// </summary>
        EveryEnter = 3,
    }

} 

