
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum SelectMode
    {
        /// <summary>
        /// 全部
        /// </summary>
        All = 1,
        /// <summary>
        /// 随机一个
        /// </summary>
        RandomOne = 2,
        /// <summary>
        /// 随机全部
        /// </summary>
        RandomCount = 3,
    }

} 

