
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    [System.Flags]
    public enum ShowRuleWeekType
    {
        /// <summary>
        /// 周一
        /// </summary>
        Monday = 1,
        /// <summary>
        /// 周二
        /// </summary>
        Tuesday = 2,
        /// <summary>
        /// 周三
        /// </summary>
        Wednesday = 4,
        /// <summary>
        /// 周四
        /// </summary>
        Thursday = 8,
        /// <summary>
        /// 周五
        /// </summary>
        Friday = 16,
        /// <summary>
        /// 周六
        /// </summary>
        Saturday = 32,
        /// <summary>
        /// 周日
        /// </summary>
        Sunday = 64,
        /// <summary>
        /// 全部
        /// </summary>
        All = 127,
    }

} 

