
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class SprayPaintGameData : Luban.BeanBase
{
    public SprayPaintGameData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ClothingID = (long)_obj.GetValue("ClothingID");
        ReferenceSpritePath = (string)_obj.GetValue("ReferenceSpritePath");
        ClothPrefabPath = (string)_obj.GetValue("ClothPrefabPath");
        { var __json0 = _obj.GetValue("PigmentColorList"); PigmentColorList = new System.Collections.Generic.List<vector3>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { vector3 __v0;  __v0 = global::XFramework.vector3.Deserializevector3(__e0);  PigmentColorList.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PieceAnswerList"); PieceAnswerList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  PieceAnswerList.Add(__v0); }   }
    }

    public static SprayPaintGameData DeserializeSprayPaintGameData(JToken _buf)
    {
        return new SprayPaintGameData(_buf);
    }

    /// <summary>
    /// 服装ID(表主键,一件服装一条)
    /// </summary>
    public readonly long ClothingID;
    /// <summary>
    /// 标准配色参考图Addressable Key
    /// </summary>
    public readonly string ReferenceSpritePath;
    /// <summary>
    /// 服饰片预制体Addressable Key(挂SprayPaintClothGroup)
    /// </summary>
    public readonly string ClothPrefabPath;
    /// <summary>
    /// 候选喷枪颜料RGB(0-255)
    /// </summary>
    public readonly System.Collections.Generic.List<vector3> PigmentColorList;
    /// <summary>
    /// 每个服饰片的正确颜料索引(顺序对应预制体服饰片,从0开始)
    /// </summary>
    public readonly System.Collections.Generic.List<int> PieceAnswerList;


    public const int __ID__ = -1937145427;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ClothingID:" + ClothingID + ","
        + "ReferenceSpritePath:" + ReferenceSpritePath + ","
        + "ClothPrefabPath:" + ClothPrefabPath + ","
        + "PigmentColorList:" + Luban.StringUtil.CollectionToString(PigmentColorList) + ","
        + "PieceAnswerList:" + Luban.StringUtil.CollectionToString(PieceAnswerList) + ","
        + "}";
    }
}
}

