
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 角色消息(伪)配置表
/// </summary>
public partial class TbChatMessageData
{
    private readonly System.Collections.Generic.Dictionary<long, ChatMessageData> _dataMap;
    private readonly System.Collections.Generic.List<ChatMessageData> _dataList;
    
    public TbChatMessageData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ChatMessageData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ChatMessageData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ChatMessageData _v;
            _v = global::XFramework.ChatMessageData.DeserializeChatMessageData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ChatMessageData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ChatMessageData> DataList => _dataList;

    public ChatMessageData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ChatMessageData Get(long key) => _dataMap[key];
    public ChatMessageData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

