
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 服装定义表
/// </summary>
public partial class TbClothingData
{
    private readonly System.Collections.Generic.Dictionary<long, ClothingData> _dataMap;
    private readonly System.Collections.Generic.List<ClothingData> _dataList;
    
    public TbClothingData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ClothingData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ClothingData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ClothingData _v;
            _v = global::XFramework.ClothingData.DeserializeClothingData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ClothingData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ClothingData> DataList => _dataList;

    public ClothingData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ClothingData Get(long key) => _dataMap[key];
    public ClothingData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

