
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 剧情背景表
/// </summary>
public partial class TbDramaBgData
{
    private readonly System.Collections.Generic.Dictionary<long, DramaBgData> _dataMap;
    private readonly System.Collections.Generic.List<DramaBgData> _dataList;
    
    public TbDramaBgData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, DramaBgData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DramaBgData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DramaBgData _v;
            _v = global::XFramework.DramaBgData.DeserializeDramaBgData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, DramaBgData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DramaBgData> DataList => _dataList;

    public DramaBgData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DramaBgData Get(long key) => _dataMap[key];
    public DramaBgData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

