
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 展会宣发表
/// </summary>
public partial class TbExhibitionPromotionData
{
    private readonly System.Collections.Generic.Dictionary<long, ExhibitionPromotionData> _dataMap;
    private readonly System.Collections.Generic.List<ExhibitionPromotionData> _dataList;
    
    public TbExhibitionPromotionData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ExhibitionPromotionData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ExhibitionPromotionData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ExhibitionPromotionData _v;
            _v = global::XFramework.ExhibitionPromotionData.DeserializeExhibitionPromotionData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ExhibitionPromotionData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ExhibitionPromotionData> DataList => _dataList;

    public ExhibitionPromotionData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ExhibitionPromotionData Get(long key) => _dataMap[key];
    public ExhibitionPromotionData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

