
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 场景配置表
/// </summary>
public partial class TbGameSceneData
{
    private readonly System.Collections.Generic.Dictionary<long, GameSceneData> _dataMap;
    private readonly System.Collections.Generic.List<GameSceneData> _dataList;
    
    public TbGameSceneData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, GameSceneData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<GameSceneData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            GameSceneData _v;
            _v = global::XFramework.GameSceneData.DeserializeGameSceneData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, GameSceneData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameSceneData> DataList => _dataList;

    public GameSceneData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameSceneData Get(long key) => _dataMap[key];
    public GameSceneData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

