
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 催稿玩法-灵感草稿库配置表
/// </summary>
public partial class TbManuscriptItemData
{
    private readonly System.Collections.Generic.Dictionary<long, ManuscriptItemData> _dataMap;
    private readonly System.Collections.Generic.List<ManuscriptItemData> _dataList;
    
    public TbManuscriptItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ManuscriptItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ManuscriptItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ManuscriptItemData _v;
            _v = global::XFramework.ManuscriptItemData.DeserializeManuscriptItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ManuscriptItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ManuscriptItemData> DataList => _dataList;

    public ManuscriptItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ManuscriptItemData Get(long key) => _dataMap[key];
    public ManuscriptItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

