
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 属性配置表
/// </summary>
public partial class TbPropertyData
{
    private readonly System.Collections.Generic.Dictionary<PropertyType, PropertyData> _dataMap;
    private readonly System.Collections.Generic.List<PropertyData> _dataList;
    
    public TbPropertyData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<PropertyType, PropertyData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PropertyData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PropertyData _v;
            _v = global::XFramework.PropertyData.DeserializePropertyData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Property, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<PropertyType, PropertyData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PropertyData> DataList => _dataList;

    public PropertyData GetOrDefault(PropertyType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PropertyData Get(PropertyType key) => _dataMap[key];
    public PropertyData this[PropertyType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

