
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 私信消息配置表
/// </summary>
public partial class TbPriavateMessageData
{
    private readonly System.Collections.Generic.Dictionary<long, PriavateMessageData> _dataMap;
    private readonly System.Collections.Generic.List<PriavateMessageData> _dataList;
    
    public TbPriavateMessageData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, PriavateMessageData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PriavateMessageData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PriavateMessageData _v;
            _v = global::XFramework.PriavateMessageData.DeserializePriavateMessageData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, PriavateMessageData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PriavateMessageData> DataList => _dataList;

    public PriavateMessageData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PriavateMessageData Get(long key) => _dataMap[key];
    public PriavateMessageData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

