
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 消耗品道具配置表
/// </summary>
public partial class TbRecipeItemData
{
    private readonly System.Collections.Generic.Dictionary<long, RecipeItemData> _dataMap;
    private readonly System.Collections.Generic.List<RecipeItemData> _dataList;
    
    public TbRecipeItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, RecipeItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<RecipeItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            RecipeItemData _v;
            _v = global::XFramework.RecipeItemData.DeserializeRecipeItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, RecipeItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RecipeItemData> DataList => _dataList;

    public RecipeItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RecipeItemData Get(long key) => _dataMap[key];
    public RecipeItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

