
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 超市商店数据
/// </summary>
public partial class TbSuperMarketShopData
{
    private readonly System.Collections.Generic.Dictionary<long, SuperMarketShopData> _dataMap;
    private readonly System.Collections.Generic.List<SuperMarketShopData> _dataList;
    
    public TbSuperMarketShopData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, SuperMarketShopData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<SuperMarketShopData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            SuperMarketShopData _v;
            _v = global::XFramework.SuperMarketShopData.DeserializeSuperMarketShopData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, SuperMarketShopData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SuperMarketShopData> DataList => _dataList;

    public SuperMarketShopData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SuperMarketShopData Get(long key) => _dataMap[key];
    public SuperMarketShopData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

