
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbUlocakPropData : Luban.BeanBase
{
    public TbUlocakPropData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        PropType = (PropertyType)(int)_obj.GetValue("PropType");
        Value = (int)_obj.GetValue("Value");
    }

    public static TbUlocakPropData DeserializeTbUlocakPropData(JToken _buf)
    {
        return new TbUlocakPropData(_buf);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public readonly PropertyType PropType;
    /// <summary>
    /// 需求数量(大于等于)
    /// </summary>
    public readonly int Value;


    public const int __ID__ = 1128612624;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PropType:" + PropType + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

