
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 解锁条件表
/// </summary>
public partial class TbUnlockConditionsData
{
    private readonly System.Collections.Generic.Dictionary<long, UnlockConditionsData> _dataMap;
    private readonly System.Collections.Generic.List<UnlockConditionsData> _dataList;
    
    public TbUnlockConditionsData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, UnlockConditionsData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<UnlockConditionsData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            UnlockConditionsData _v;
            _v = global::XFramework.UnlockConditionsData.DeserializeUnlockConditionsData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, UnlockConditionsData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UnlockConditionsData> DataList => _dataList;

    public UnlockConditionsData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UnlockConditionsData Get(long key) => _dataMap[key];
    public UnlockConditionsData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

