
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 世界地图配置表
/// </summary>
public partial class TbWordMapSceneData
{
    private readonly System.Collections.Generic.Dictionary<long, WordMapSceneData> _dataMap;
    private readonly System.Collections.Generic.List<WordMapSceneData> _dataList;
    
    public TbWordMapSceneData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, WordMapSceneData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<WordMapSceneData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            WordMapSceneData _v;
            _v = global::XFramework.WordMapSceneData.DeserializeWordMapSceneData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, WordMapSceneData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<WordMapSceneData> DataList => _dataList;

    public WordMapSceneData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public WordMapSceneData Get(long key) => _dataMap[key];
    public WordMapSceneData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

