
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class UnlockConditionsData : Luban.BeanBase
{
    public UnlockConditionsData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        UnlockConditionsType = (UnlockConditionsType)(int)_obj.GetValue("UnlockConditionsType");
        TbUlocakPropData = global::XFramework.TbUlocakPropData.DeserializeTbUlocakPropData(_obj.GetValue("TbUlocakPropData"));
        TbUlocakItemData = global::XFramework.TbUlocakItemData.DeserializeTbUlocakItemData(_obj.GetValue("TbUlocakItemData"));
        TbUlockCharacterData = global::XFramework.TbUlockCharacterData.DeserializeTbUlockCharacterData(_obj.GetValue("TbUlockCharacterData"));
        TbUlockDateData = global::XFramework.TbUlockDateData.DeserializeTbUlockDateData(_obj.GetValue("TbUlockDateData"));
    }

    public static UnlockConditionsData DeserializeUnlockConditionsData(JToken _buf)
    {
        return new UnlockConditionsData(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 解锁类型
    /// </summary>
    public readonly UnlockConditionsType UnlockConditionsType;
    /// <summary>
    /// 属性解锁
    /// </summary>
    public readonly TbUlocakPropData TbUlocakPropData;
    /// <summary>
    /// 物品解锁
    /// </summary>
    public readonly TbUlocakItemData TbUlocakItemData;
    /// <summary>
    /// 角色属性解锁
    /// </summary>
    public readonly TbUlockCharacterData TbUlockCharacterData;
    /// <summary>
    /// 时间阶段
    /// </summary>
    public readonly TbUlockDateData TbUlockDateData;


    public const int __ID__ = -1488693498;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TbUlocakPropData?.ResolveRef(tables);
        TbUlocakItemData?.ResolveRef(tables);
        TbUlockCharacterData?.ResolveRef(tables);
        TbUlockDateData?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "UnlockConditionsType:" + UnlockConditionsType + ","
        + "TbUlocakPropData:" + TbUlocakPropData + ","
        + "TbUlocakItemData:" + TbUlocakItemData + ","
        + "TbUlockCharacterData:" + TbUlockCharacterData + ","
        + "TbUlockDateData:" + TbUlockDateData + ","
        + "}";
    }
}
}

