// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class UpperSlot
{
    private UnityEngine.UI.Image icon;
    private UnityEngine.UI.Image selected;
    private UnityEngine.RectTransform complete;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("icon");
        selected = Get<UnityEngine.UI.Image>("selected");
        complete = Get<UnityEngine.RectTransform>("Complete");

    }
}
