// <auto-generated />
using UnityEngine;

public partial class PopClawMachineTipUI
{
    private UnityEngine.RectTransform uIMask;
    private UnityEngine.Localization.Components.LocalizeStringEvent valueTex;
    private TMPro.TextMeshProUGUI number;
    private CustomButton addGameNumberBtn;
    private CustomButton startGameButton;

    private void InitAutoBind()
    {
        uIMask = Get<UnityEngine.RectTransform>("UIMask");
        valueTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/Page/Top/GameTips/ValueTex");
        number = Get<TMPro.TextMeshProUGUI>("UIMask/Page/Info/GamePropInfo/Number");
        addGameNumberBtn = Get<CustomButton>("UIMask/Page/Info/AddGameNumberBtn");
        startGameButton = Get<CustomButton>("UIMask/Page/StartGameButton");

    }
}
