// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ClothingPatternMakingUI
{
    private UnityEngine.Localization.Components.LocalizeStringEvent nameStr;
    private UnityEngine.Localization.Components.LocalizeStringEvent descStr;
    private UnityEngine.UI.Image icon;
    private UnityEngine.RectTransform pCB;
    private UnityEngine.RectTransform memuSlotGroup;
    private CustomButton closeButton;
    private EditorButtonGroups editorButtonGroups;
    private CustomButton completeBtn;

    private void InitAutoBind()
    {
        nameStr = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/background/Image/NameStr");
        descStr = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/background/Image/DescStr");
        icon = Get<UnityEngine.UI.Image>("UIMask/background/Image/background/icon");
        pCB = Get<UnityEngine.RectTransform>("UIMask/background/RightBackground/PCB");
        memuSlotGroup = Get<UnityEngine.RectTransform>("UIMask/background/RightBackground/MemuSlotGroup");
        closeButton = Get<CustomButton>("UIMask/CloseButton");
        editorButtonGroups = Get<EditorButtonGroups>("UIMask/EditorButtonGroups");
        completeBtn = Get<CustomButton>("UIMask/background/RightBackground/CompleteButton/CompleteBtn");

    }
}
