// <auto-generated />
using UnityEngine;

public partial class PopExhibitionSettlementUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private UnityEngine.Localization.Components.LocalizeStringEvent settlementValTex;
    private TMPro.TextMeshProUGUI coinTotalValueTex;
    private TMPro.TextMeshProUGUI fenTotalValue;
    private TMPro.TextMeshProUGUI goodwillTotalValue;
    private UnityEngine.Localization.Components.LocalizeStringEvent settlementProcessVal;
    private UnityEngine.Localization.Components.LocalizeStringEvent completeValTex;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/Background/Bg_1/Leff/Scroll View");
        settlementValTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/Background/Bg_1/Leff/SettlementValTex");
        coinTotalValueTex = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Bg_1/Right/TotalFarme/Coin/CoinTotalValueTex");
        fenTotalValue = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Bg_1/Right/TotalFarme/Fen/FenTotalValue");
        goodwillTotalValue = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Bg_1/Right/TotalFarme/Goodwill/GoodwillTotalValue");
        settlementProcessVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/Background/Bg_1/Leff/SettlementProcessVal");
        completeValTex = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/Background/Bg_1/Leff/CompleteValTex");

    }
}
