// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopFailWindows
{
    private UnityEngine.UI.Button btnReset;
    private UnityEngine.UI.Button btnQueren;

    private void InitAutoBind()
    {
        btnReset = Get<UnityEngine.UI.Button>("UIMask/MaskBlack/anniu/btn_reset");
        btnQueren = Get<UnityEngine.UI.Button>("UIMask/MaskBlack/anniu/btn_queren");

    }
}
