// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using UnityEngine;

public partial class ScreenActionController
{
    private FadeController fadeController;

    private void InitAutoBind()
    {
        fadeController = Get<FadeController>("FadeController");

    }


  
}
