// <auto-generated />
using UnityEngine;

public partial class PromotionSlot
{
    private UnityEngine.Localization.Components.LocalizeStringEvent nameString;
    private UnityEngine.Localization.Components.LocalizeStringEvent valueString;
    private CustomButton buyButton;
    private TMPro.TextMeshProUGUI value;

    private void InitAutoBind()
    {
        nameString = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("NameString");
        valueString = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("ValueString");
        buyButton = Get<CustomButton>("BuyButton");
        value = Get<TMPro.TextMeshProUGUI>("BuyButton/Value");

    }
}
