// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class TalkContentController
{
    private UnityEngine.RectTransform normal;
    private UnityEngine.RectTransform hCG;
    private Febucci.TextAnimatorForUnity.TypewriterComponent talkNormalContext;
    private Febucci.TextAnimatorForUnity.TypewriterComponent talkHCGContext;

    private void InitAutoBind()
    {
        normal = Get<UnityEngine.RectTransform>("Normal");
        hCG = Get<UnityEngine.RectTransform>("HCG");
        talkNormalContext = Get<Febucci.TextAnimatorForUnity.TypewriterComponent>("Normal/TalkNormalContext");
        talkHCGContext = Get<Febucci.TextAnimatorForUnity.TypewriterComponent>("HCG/TalkHCGContext");

    }
}
