// <auto-generated />
using UnityEngine;

public partial class PrivateMessagePage
{
    private UnityEngine.RectTransform messageInfo;
    private UnityEngine.RectTransform message;
    private SelectedButton startReplyButton;

    private void InitAutoBind()
    {
        messageInfo = Get<UnityEngine.RectTransform>("MessageInfo");
        message = Get<UnityEngine.RectTransform>("Message");
        startReplyButton = Get<SelectedButton>("MessageInfo/background/StartReplyFarme/StartReplyButton");

    }
}
