// <auto-generated />
using UnityEngine;

public partial class ExhibitionGameUI
{
    private TMPro.TextMeshProUGUI timeVal;
    private TMPro.TextMeshProUGUI goldVal;
    private UnityEngine.UI.Slider superSlider;
    private UnityEngine.RectTransform characterFarme;
    private PathologicalGames.SpawnPool pools;
    private RubbishController rubbishController;
    private UnityEngine.Localization.Components.LocalizeStringEvent stockVal;
    private Coffee.UIEffects.UIEffectTweener fill;

    private void InitAutoBind()
    {
        timeVal = Get<TMPro.TextMeshProUGUI>("UIMask/Top/Time/TimeVal");
        goldVal = Get<TMPro.TextMeshProUGUI>("UIMask/Top/GoldVal/GoldVal");
        superSlider = Get<UnityEngine.UI.Slider>("UIMask/Top/SuperSlider");
        characterFarme = Get<UnityEngine.RectTransform>("UIMask/CharacterFarme");
        pools = Get<PathologicalGames.SpawnPool>("UIMask/Pools");
        rubbishController = Get<RubbishController>("UIMask/MainFarme/LeftMenums/RubbishController");
        stockVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("UIMask/DownFarme/inStockFarme/StockVal");
        fill = Get<Coffee.UIEffects.UIEffectTweener>("UIMask/Top/SuperSlider/Fill Area/Fill");

    }
}
