// <auto-generated />
using UnityEngine;

public partial class ExhibitionGameUI
{
    private TMPro.TextMeshProUGUI timeVal;
    private TMPro.TextMeshProUGUI goldVal;
    private UnityEngine.RectTransform superSlider;

    private void InitAutoBind()
    {
        timeVal = Get<TMPro.TextMeshProUGUI>("UIMask/Top/Time/TimeVal");
        goldVal = Get<TMPro.TextMeshProUGUI>("UIMask/Top/GoldVal/GoldVal");
        superSlider = Get<UnityEngine.RectTransform>("UIMask/Top/SuperSlider");

    }
}
