// <auto-generated />
using UnityEngine;

public partial class RubbishController
{
    private TMPro.TextMeshProUGUI nameString;

    private void InitAutoBind()
    {
        nameString = Get<TMPro.TextMeshProUGUI>("NameString");

    }
}
