// <auto-generated />
using UnityEngine;

public partial class ExhibitionPage
{
    private UnityEngine.UI.Image exhibitionBg;
    private UnityEngine.Localization.Components.LocalizeStringEvent exhibitionDesc;
    private UnityEngine.Localization.Components.LocalizeStringEvent starDateTimeValue;
    private UnityEngine.Localization.Components.LocalizeStringEvent stateValue;
    private UnityEngine.Localization.Components.LocalizeStringEvent exposureVal;
    private UnityEngine.Localization.Components.LocalizeStringEvent exhibitionName;

    private void InitAutoBind()
    {
        exhibitionBg = Get<UnityEngine.UI.Image>("background/Main/info/ExhibitionBg");
        exhibitionDesc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("background/Main/info/ExhibitionDesc");
        starDateTimeValue = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("background/Main/PrepareFarme/StarDateTimeFarme/StarDateTimeValue");
        stateValue = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("background/Main/PrepareFarme/StateFarme/StateValue");
        exposureVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("background/Main/PrepareFarme/ExposureVal");
        exhibitionName = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("background/Main/ExhibitionName");

    }
}
