// <auto-generated />
using UnityEngine;

public partial class PostingUpdatesPage
{
    private UnityEngine.UI.ScrollRect mScrollRect;
    private UnityEngine.Localization.Components.LocalizeStringEvent desc;
    private UnityEngine.UI.Button randomButton;
    private UnityEngine.Localization.Components.LocalizeStringEvent selectedPictureText;
    private SelectedButton sendButton;
    private UnityEngine.RectTransform inputSlot;

    private void InitAutoBind()
    {
        mScrollRect = Get<UnityEngine.UI.ScrollRect>("mScrollRect");
        desc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("mScrollRect/Content/InputSlot/MessageSlot/DescLayoutGroup/Desc");
        randomButton = Get<UnityEngine.UI.Button>("mScrollRect/Content/InputSlot/MessageSlot/DescLayoutGroup/Desc/randomButton");
        selectedPictureText = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("mScrollRect/Content/InputSlot/Image/SelectedPictureText");
        sendButton = Get<SelectedButton>("mScrollRect/Content/InputSlot/MaterialViews_1/SendButton");
        inputSlot = Get<UnityEngine.RectTransform>("mScrollRect/Content/InputSlot");

    }
}
