// <auto-generated />
using UnityEngine;

public partial class GarmentMakingCommonUI
{
    private CustomButton onlineGameButton;
    private CustomButton garmentMakingButton;
    private CustomButton sleepButton;

    private void InitAutoBind()
    {
        onlineGameButton = Get<CustomButton>("UIMask/GarmentMakingButton");
        garmentMakingButton = Get<CustomButton>("UIMask/OnineGameButton");
        sleepButton = Get<CustomButton>("UIMask/SleepButton");

    }
}
