// <auto-generated />
using UnityEngine;

public partial class MerchandiseRuntimeSlot
{
    private TMPro.TextMeshProUGUI itemCountVal;
    private UnityEngine.UI.Image mask;
    private UnityEngine.UI.Image itemIcon;
    private UnityEngine.UI.Image farmeImg;
    private UnityEngine.Localization.Components.LocalizeStringEvent priceVal;

    private void InitAutoBind()
    {
        itemCountVal = Get<TMPro.TextMeshProUGUI>("ItemBag/ItemCountVal");
        mask = Get<UnityEngine.UI.Image>("ItemBag/Mask");
        itemIcon = Get<UnityEngine.UI.Image>("ItemBag/Mask/itemIcon");
        farmeImg = Get<UnityEngine.UI.Image>("ItemBag/FarmeImg");
        priceVal = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("PriceFarme/PriceVal");

    }
}
