// <auto-generated />
using UnityEngine;

public partial class ClothingAssetsSlot
{
    private UnityEngine.UI.Image clothingImg;
    private UnityEngine.UI.Image lockStatus;
    private UnityEngine.Localization.Components.LocalizeStringEvent clothing;
    private Coffee.UIEffects.UIEffect farme;

    private void InitAutoBind()
    {
        clothingImg = Get<UnityEngine.UI.Image>("Farme/ClothingImg");
        lockStatus = Get<UnityEngine.UI.Image>("LockStatus");
        clothing = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("ClothingName");
        farme = Get<Coffee.UIEffects.UIEffect>("Farme");

    }
}
