// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class RacingCarSewingMachinesUI
{
    private CustomButton btnTuichu;

    private void InitAutoBind()
    {
        btnTuichu = Get<CustomButton>("UIMask/btn_tuichu");

    }
}
