// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopCompleteWindow
{
    private CustomButton btnQueren;

    private void InitAutoBind()
    {
        btnQueren = Get<CustomButton>("UIMask/Background/btn_queren");

    }
}
