// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopCompleteWindow
{
    private CustomButton btnQueren;
    private CustomButton btnNext;

    private void InitAutoBind()
    {
        btnQueren = Get<CustomButton>("UIMask/Background/anniu/btn_queren");
        btnNext = Get<CustomButton>("UIMask/Background/anniu/btn_next");

    }
}
