// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class DramaRuntimeUI
{
    private TalkActionController talkActionController;
    private ScreenActionController screenActionController;
    private ActorController actorController;
    private OptionController optionController;
    private UnityEngine.UI.Button onClikc;

    private void InitAutoBind()
    {
        talkActionController = Get<TalkActionController>("Page/TalkActionController");
        screenActionController = Get<ScreenActionController>("Page/ScreenActionController");
        actorController = Get<ActorController>("Page/ActorController");
        optionController = Get<OptionController>("Page/OptionController");
        onClikc = Get<UnityEngine.UI.Button>("Page/OnClikc");

        InitBoundUI(talkActionController);
        InitBoundUI(screenActionController);
        InitBoundUI(actorController);
        InitBoundUI(optionController);

    }

    private static void InitBoundUI(XFramework.UIBase target)
    {
        if (target != null)
        {
            target.Init();
        }
    }
}
