// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class MoldSlot
{
    private UnityEngine.UI.Image gameMask;
    private UnityEngine.UI.Image gameIcon;

    private void InitAutoBind()
    {
        gameMask = Get<UnityEngine.UI.Image>("GameMask");
        gameIcon = Get<UnityEngine.UI.Image>("GameIcon");

    }
}
