
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterShowRuleData : Luban.BeanBase
{
    public CharacterShowRuleData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        SceneLocation = (long)_obj.GetValue("SceneLocation");
        TriggerCondition = (string)_obj.GetValue("TriggerCondition");
        WeekType = (ShowRuleWeekType)(int)_obj.GetValue("WeekType");
        AppearanceTime = (ShowRuleTimeType)(int)_obj.GetValue("AppearanceTime");
        ScenePosition = global::XFramework.vector2.Deserializevector2(_obj.GetValue("ScenePosition"));
    }

    public static CharacterShowRuleData DeserializeCharacterShowRuleData(JToken _buf)
    {
        return new CharacterShowRuleData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 出现场景
    /// </summary>
    public readonly long SceneLocation;
    /// <summary>
    /// 出现条件
    /// </summary>
    public readonly string TriggerCondition;
    /// <summary>
    /// 出现周天
    /// </summary>
    public readonly ShowRuleWeekType WeekType;
    /// <summary>
    /// 出现时间段
    /// </summary>
    public readonly ShowRuleTimeType AppearanceTime;
    /// <summary>
    /// 出现位置
    /// </summary>
    public readonly vector2 ScenePosition;


    public const int __ID__ = -1227491188;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SceneLocation:" + SceneLocation + ","
        + "TriggerCondition:" + TriggerCondition + ","
        + "WeekType:" + WeekType + ","
        + "AppearanceTime:" + AppearanceTime + ","
        + "ScenePosition:" + ScenePosition + ","
        + "}";
    }
}
}

