
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum CharacterPropType
    {
        /// <summary>
        /// 心情值
        /// </summary>
        Feeling = 1,
        /// <summary>
        /// 好感值
        /// </summary>
        Goodwill = 2,
    }

} 

