
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterData : Luban.BeanBase
{
    public CharacterData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        { var __json0 = _obj.GetValue("FavorMax"); FavorMax = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  FavorMax.Add(__v0); }   }
        FavorStageReward = (string)_obj.GetValue("FavorStageReward");
        FavorUnlock = (string)_obj.GetValue("FavorUnlock");
    }

    public static CharacterData DeserializeCharacterData(JToken _buf)
    {
        return new CharacterData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 好感度上限
    /// </summary>
    public readonly System.Collections.Generic.List<long> FavorMax;
    /// <summary>
    /// 好感度阶段奖励
    /// </summary>
    public readonly string FavorStageReward;
    /// <summary>
    /// 好感解锁
    /// </summary>
    public readonly string FavorUnlock;


    public const int __ID__ = -991456685;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "FavorMax:" + Luban.StringUtil.CollectionToString(FavorMax) + ","
        + "FavorStageReward:" + FavorStageReward + ","
        + "FavorUnlock:" + FavorUnlock + ","
        + "}";
    }
}
}

