
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ChatMessageData : Luban.BeanBase
{
    public ChatMessageData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Message = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Message"));
    }

    public static ChatMessageData DeserializeChatMessageData(JToken _buf)
    {
        return new ChatMessageData(_buf);
    }

    /// <summary>
    /// 消息ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly TbLocalzationKeyData Message;


    public const int __ID__ = 1375915449;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Message?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Message:" + Message + ","
        + "}";
    }
}
}

