
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ClothingData : Luban.BeanBase
{
    public ClothingData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        ClothingName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("ClothingName"));
        ClothingIconName = (string)_obj.GetValue("ClothingIconName");
        { var __json0 = _obj.GetValue("AccessoriesList"); AccessoriesList = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  AccessoriesList.Add(__v0); }   }
        ExposureValue = (int)_obj.GetValue("ExposureValue");
        MinGameType = (ClothingMinGameType)(int)_obj.GetValue("MinGameType");
        GemIconName = (string)_obj.GetValue("GemIconName");
        SmartGemPaht = (string)_obj.GetValue("SmartGemPaht");
    }

    public static ClothingData DeserializeClothingData(JToken _buf)
    {
        return new ClothingData(_buf);
    }

    /// <summary>
    /// 服装表ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 服装名称
    /// </summary>
    public readonly TbLocalzationKeyData ClothingName;
    /// <summary>
    /// 服装图标
    /// </summary>
    public readonly string ClothingIconName;
    /// <summary>
    /// 配件列表
    /// </summary>
    public readonly System.Collections.Generic.List<long> AccessoriesList;
    /// <summary>
    /// 曝光值
    /// </summary>
    public readonly int ExposureValue;
    /// <summary>
    /// 解锁小游戏
    /// </summary>
    public readonly ClothingMinGameType MinGameType;
    /// <summary>
    /// 宝石Icon
    /// </summary>
    public readonly string GemIconName;
    /// <summary>
    /// 宝石样式预制体
    /// </summary>
    public readonly string SmartGemPaht;


    public const int __ID__ = -1774354574;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ClothingName?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "ClothingName:" + ClothingName + ","
        + "ClothingIconName:" + ClothingIconName + ","
        + "AccessoriesList:" + Luban.StringUtil.CollectionToString(AccessoriesList) + ","
        + "ExposureValue:" + ExposureValue + ","
        + "MinGameType:" + MinGameType + ","
        + "GemIconName:" + GemIconName + ","
        + "SmartGemPaht:" + SmartGemPaht + ","
        + "}";
    }
}
}

