
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ClothingMinGameType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 熨斗小游戏
        /// </summary>
        SewingMachine = 1,
        /// <summary>
        /// 拼图小游戏
        /// </summary>
        Puzzle = 2,
        /// <summary>
        /// 滴胶固化小游戏
        /// </summary>
        MedicinalSolution = 3,
    }

} 

