
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ClothingAccessoriesData : Luban.BeanBase
{
    public ClothingAccessoriesData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        AccessoriesName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("AccessoriesName"));
        AccessoriesIconName = (string)_obj.GetValue("AccessoriesIconName");
        { var __json0 = _obj.GetValue("Consumption"); Consumption = new System.Collections.Generic.List<TbConsumption>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbConsumption __v0;  __v0 = global::XFramework.TbConsumption.DeserializeTbConsumption(__e0);  Consumption.Add(__v0); }   }
    }

    public static ClothingAccessoriesData DeserializeClothingAccessoriesData(JToken _buf)
    {
        return new ClothingAccessoriesData(_buf);
    }

    /// <summary>
    /// 配件ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 配件多语言Key
    /// </summary>
    public readonly TbLocalzationKeyData AccessoriesName;
    /// <summary>
    /// 图标名称
    /// </summary>
    public readonly string AccessoriesIconName;
    /// <summary>
    /// 消耗道具配置
    /// </summary>
    public readonly System.Collections.Generic.List<TbConsumption> Consumption;


    public const int __ID__ = 787362354;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AccessoriesName?.ResolveRef(tables);
        foreach (var _e in Consumption) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "AccessoriesName:" + AccessoriesName + ","
        + "AccessoriesIconName:" + AccessoriesIconName + ","
        + "Consumption:" + Luban.StringUtil.CollectionToString(Consumption) + ","
        + "}";
    }
}
}

