
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DialogueData : Luban.BeanBase
{
    public DialogueData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        PlotModule = (long)_obj.GetValue("PlotModule");
        DisplayAnimId = (long)_obj.GetValue("DisplayAnimId");
        SpeakerId = (long)_obj.GetValue("SpeakerId");
        DlgType = (DialogueType)(int)_obj.GetValue("DlgType");
        DlgText = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("DlgText"));
        NextDlgId = (long)_obj.GetValue("NextDlgId");
        { var __json0 = _obj.GetValue("OptGrpId"); OptGrpId = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  OptGrpId.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PreReqDlgId"); PreReqDlgId = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PreReqDlgId.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PreconditionId"); PreconditionId = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PreconditionId.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PostDlgEventId"); PostDlgEventId = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PostDlgEventId.Add(__v0); }   }
        DlgPriority = (DlgPriorityType)(int)_obj.GetValue("DlgPriority");
        IsSkippable = (bool)_obj.GetValue("IsSkippable");
        SaveFlag = (bool)_obj.GetValue("SaveFlag");
        AutoPlayDuration = (int)_obj.GetValue("AutoPlayDuration");
        SfxId = (long)_obj.GetValue("SfxId");
        BgmId = (long)_obj.GetValue("BgmId");
        BgImageId = (long)_obj.GetValue("BgImageId");
        BubbleStyleId = (int)_obj.GetValue("BubbleStyleId");
        SpritePos = (LlustrationDirection)(int)_obj.GetValue("SpritePos");
        PrevSpriteHandle = (PrevSpriteHandleType)(int)_obj.GetValue("PrevSpriteHandle");
    }

    public static DialogueData DeserializeDialogueData(JToken _buf)
    {
        return new DialogueData(_buf);
    }

    /// <summary>
    /// 对话序号
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 所属剧情模块
    /// </summary>
    public readonly long PlotModule;
    /// <summary>
    /// 显示动画 ID
    /// </summary>
    public readonly long DisplayAnimId;
    /// <summary>
    /// 说话人
    /// </summary>
    public readonly long SpeakerId;
    /// <summary>
    /// 对话类型
    /// </summary>
    public readonly DialogueType DlgType;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly TbLocalzationKeyData DlgText;
    /// <summary>
    /// 下一句对话ID
    /// </summary>
    public readonly long NextDlgId;
    /// <summary>
    /// 选项组ID
    /// </summary>
    public readonly System.Collections.Generic.List<long> OptGrpId;
    /// <summary>
    /// 对话前置完成对话 ID
    /// </summary>
    public readonly System.Collections.Generic.List<long> PreReqDlgId;
    /// <summary>
    /// 进入对话前置条件ID
    /// </summary>
    public readonly System.Collections.Generic.List<long> PreconditionId;
    /// <summary>
    /// 对话结束后触发奖励ID
    /// </summary>
    public readonly System.Collections.Generic.List<long> PostDlgEventId;
    /// <summary>
    /// 对话优先级
    /// </summary>
    public readonly DlgPriorityType DlgPriority;
    /// <summary>
    /// 对话是否可跳过
    /// </summary>
    public readonly bool IsSkippable;
    /// <summary>
    /// 对话存档标记
    /// </summary>
    public readonly bool SaveFlag;
    /// <summary>
    /// 对话自动播放时长
    /// </summary>
    public readonly int AutoPlayDuration;
    /// <summary>
    /// 音效ID
    /// </summary>
    public readonly long SfxId;
    /// <summary>
    /// 背景音乐ID
    /// </summary>
    public readonly long BgmId;
    /// <summary>
    /// 背景图ID
    /// </summary>
    public readonly long BgImageId;
    /// <summary>
    /// 对话气泡样式 ID
    /// </summary>
    public readonly int BubbleStyleId;
    /// <summary>
    /// 立绘位置
    /// </summary>
    public readonly LlustrationDirection SpritePos;
    /// <summary>
    /// 上一个对话人立绘处理
    /// </summary>
    public readonly PrevSpriteHandleType PrevSpriteHandle;


    public const int __ID__ = 1514857922;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        DlgText?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "PlotModule:" + PlotModule + ","
        + "DisplayAnimId:" + DisplayAnimId + ","
        + "SpeakerId:" + SpeakerId + ","
        + "DlgType:" + DlgType + ","
        + "DlgText:" + DlgText + ","
        + "NextDlgId:" + NextDlgId + ","
        + "OptGrpId:" + Luban.StringUtil.CollectionToString(OptGrpId) + ","
        + "PreReqDlgId:" + Luban.StringUtil.CollectionToString(PreReqDlgId) + ","
        + "PreconditionId:" + Luban.StringUtil.CollectionToString(PreconditionId) + ","
        + "PostDlgEventId:" + Luban.StringUtil.CollectionToString(PostDlgEventId) + ","
        + "DlgPriority:" + DlgPriority + ","
        + "IsSkippable:" + IsSkippable + ","
        + "SaveFlag:" + SaveFlag + ","
        + "AutoPlayDuration:" + AutoPlayDuration + ","
        + "SfxId:" + SfxId + ","
        + "BgmId:" + BgmId + ","
        + "BgImageId:" + BgImageId + ","
        + "BubbleStyleId:" + BubbleStyleId + ","
        + "SpritePos:" + SpritePos + ","
        + "PrevSpriteHandle:" + PrevSpriteHandle + ","
        + "}";
    }
}
}

