
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DollCatalogData : Luban.BeanBase
{
    public DollCatalogData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        UlockImageName = (string)_obj.GetValue("ulockImageName");
    }

    public static DollCatalogData DeserializeDollCatalogData(JToken _buf)
    {
        return new DollCatalogData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 未解锁状态图片
    /// </summary>
    public readonly string UlockImageName;


    public const int __ID__ = -754655496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "ulockImageName:" + UlockImageName + ","
        + "}";
    }
}
}

