
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DollCatalogData : Luban.BeanBase
{
    public DollCatalogData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        UlockImageName = (string)_obj.GetValue("ulockImageName");
        Weight = (int)_obj.GetValue("Weight");
        PrefabPath = (string)_obj.GetValue("PrefabPath");
        IsUnlockRandom = (bool)_obj.GetValue("isUnlockRandom");
        Scale = global::XFramework.vector3.Deserializevector3(_obj.GetValue("Scale"));
    }

    public static DollCatalogData DeserializeDollCatalogData(JToken _buf)
    {
        return new DollCatalogData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 未解锁状态图片
    /// </summary>
    public readonly string UlockImageName;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 是否可重复获取
    /// </summary>
    public readonly bool IsUnlockRandom;
    /// <summary>
    /// 缩放比例
    /// </summary>
    public readonly vector3 Scale;


    public const int __ID__ = -754655496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "ulockImageName:" + UlockImageName + ","
        + "Weight:" + Weight + ","
        + "PrefabPath:" + PrefabPath + ","
        + "isUnlockRandom:" + IsUnlockRandom + ","
        + "Scale:" + Scale + ","
        + "}";
    }
}
}

