
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DramaBgData : Luban.BeanBase
{
    public DramaBgData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        BgName = (string)_obj.GetValue("BgName");
        BgPath = (string)_obj.GetValue("BgPath");
    }

    public static DramaBgData DeserializeDramaBgData(JToken _buf)
    {
        return new DramaBgData(_buf);
    }

    /// <summary>
    /// 背景ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// XX
    /// </summary>
    public readonly string BgName;
    /// <summary>
    /// 背景路径
    /// </summary>
    public readonly string BgPath;


    public const int __ID__ = 1072310966;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BgName:" + BgName + ","
        + "BgPath:" + BgPath + ","
        + "}";
    }
}
}

