
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DramaCGData : Luban.BeanBase
{
    public DramaCGData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        CGPrefabPath = (string)_obj.GetValue("CGPrefabPath");
    }

    public static DramaCGData DeserializeDramaCGData(JToken _buf)
    {
        return new DramaCGData(_buf);
    }

    /// <summary>
    /// CG_ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// CG全屏Live2D 地址
    /// </summary>
    public readonly string CGPrefabPath;


    public const int __ID__ = 1071387445;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "CGPrefabPath:" + CGPrefabPath + ","
        + "}";
    }
}
}

