
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ExhibitionInfoData : Luban.BeanBase
{
    public ExhibitionInfoData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        StartDateTime = (long)_obj.GetValue("StartDateTime");
        ExhibitionInfoName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("ExhibitionInfoName"));
        Desc = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Desc"));
        { var __json0 = _obj.GetValue("PopularityData"); PopularityData = new System.Collections.Generic.List<TbPopularityData>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbPopularityData __v0;  __v0 = global::XFramework.TbPopularityData.DeserializeTbPopularityData(__e0);  PopularityData.Add(__v0); }   }
    }

    public static ExhibitionInfoData DeserializeExhibitionInfoData(JToken _buf)
    {
        return new ExhibitionInfoData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 开启时间
    /// </summary>
    public readonly long StartDateTime;
    /// <summary>
    /// 展会名称
    /// </summary>
    public readonly TbLocalzationKeyData ExhibitionInfoName;
    /// <summary>
    /// 展会描述
    /// </summary>
    public readonly TbLocalzationKeyData Desc;
    /// <summary>
    /// 人气选手
    /// </summary>
    public readonly System.Collections.Generic.List<TbPopularityData> PopularityData;


    public const int __ID__ = -774784889;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ExhibitionInfoName?.ResolveRef(tables);
        Desc?.ResolveRef(tables);
        foreach (var _e in PopularityData) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "StartDateTime:" + StartDateTime + ","
        + "ExhibitionInfoName:" + ExhibitionInfoName + ","
        + "Desc:" + Desc + ","
        + "PopularityData:" + Luban.StringUtil.CollectionToString(PopularityData) + ","
        + "}";
    }
}
}

