
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ExhibitionInfoData : Luban.BeanBase
{
    public ExhibitionInfoData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        IconName = (string)_obj.GetValue("IconName");
        ExhibitionInfoName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("ExhibitionInfoName"));
        Desc = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Desc"));
        TargetClothingID = (long)_obj.GetValue("TargetClothingID");
        AdditionValue = (float)_obj.GetValue("AdditionValue");
        ExhibitionTargetFans = (long)_obj.GetValue("ExhibitionTargetFans");
        GameTime = (float)_obj.GetValue("GameTime");
        UpdateInterval = global::XFramework.vector2.Deserializevector2(_obj.GetValue("UpdateInterval"));
        DwellTime = (float)_obj.GetValue("DwellTime");
        SuperCount = (int)_obj.GetValue("SuperCount");
        SuperTimer = (float)_obj.GetValue("SuperTimer");
        GoodwillValue = (int)_obj.GetValue("GoodwillValue");
    }

    public static ExhibitionInfoData DeserializeExhibitionInfoData(JToken _buf)
    {
        return new ExhibitionInfoData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 图片名字
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 展会名称
    /// </summary>
    public readonly TbLocalzationKeyData ExhibitionInfoName;
    /// <summary>
    /// 展会描述
    /// </summary>
    public readonly TbLocalzationKeyData Desc;
    /// <summary>
    /// 目标服装
    /// </summary>
    public readonly long TargetClothingID;
    /// <summary>
    /// 加成值
    /// </summary>
    public readonly float AdditionValue;
    /// <summary>
    /// 展会目标粉丝数
    /// </summary>
    public readonly long ExhibitionTargetFans;
    /// <summary>
    /// 展会游戏时间
    /// </summary>
    public readonly float GameTime;
    /// <summary>
    /// 刷新间隔
    /// </summary>
    public readonly vector2 UpdateInterval;
    /// <summary>
    /// 顾客停顿时间
    /// </summary>
    public readonly float DwellTime;
    /// <summary>
    /// 超级时间所需接待数量
    /// </summary>
    public readonly int SuperCount;
    /// <summary>
    /// 超级时间持续时间
    /// </summary>
    public readonly float SuperTimer;
    /// <summary>
    /// 好感度上限增加
    /// </summary>
    public readonly int GoodwillValue;


    public const int __ID__ = -774784889;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ExhibitionInfoName?.ResolveRef(tables);
        Desc?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "IconName:" + IconName + ","
        + "ExhibitionInfoName:" + ExhibitionInfoName + ","
        + "Desc:" + Desc + ","
        + "TargetClothingID:" + TargetClothingID + ","
        + "AdditionValue:" + AdditionValue + ","
        + "ExhibitionTargetFans:" + ExhibitionTargetFans + ","
        + "GameTime:" + GameTime + ","
        + "UpdateInterval:" + UpdateInterval + ","
        + "DwellTime:" + DwellTime + ","
        + "SuperCount:" + SuperCount + ","
        + "SuperTimer:" + SuperTimer + ","
        + "GoodwillValue:" + GoodwillValue + ","
        + "}";
    }
}
}

