
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ExhibitionPromotionData : Luban.BeanBase
{
    public ExhibitionPromotionData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        PromotionName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("PromotionName"));
        ExposureValue = (int)_obj.GetValue("ExposureValue");
        Price = (int)_obj.GetValue("Price");
    }

    public static ExhibitionPromotionData DeserializeExhibitionPromotionData(JToken _buf)
    {
        return new ExhibitionPromotionData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly TbLocalzationKeyData PromotionName;
    /// <summary>
    /// 增加曝光值
    /// </summary>
    public readonly int ExposureValue;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;


    public const int __ID__ = -132812482;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PromotionName?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "PromotionName:" + PromotionName + ","
        + "ExposureValue:" + ExposureValue + ","
        + "Price:" + Price + ","
        + "}";
    }
}
}

