
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    [System.Flags]
    public enum FunctionGrpup
    {
        /// <summary>
        /// 无任何功能
        /// </summary>
        Node = 0,
        /// <summary>
        /// 1=对话（如果有对话，每日第一次对话增加好感，读取通用配置）
        /// </summary>
        Dialogue = 1,
        /// <summary>
        /// 2=好感
        /// </summary>
        Goodwill = 2,
        /// <summary>
        /// 3=送礼
        /// </summary>
        GiftGiving = 4,
        /// <summary>
        /// 4=厨房
        /// </summary>
        Kitchen = 8,
        /// <summary>
        /// 5=娃娃机
        /// </summary>
        ClawMachine = 16,
        /// <summary>
        /// 6=爆点游戏
        /// </summary>
        ExplosiveGames = 32,
        /// <summary>
        /// 7=女巫毒药
        /// </summary>
        WitchsPoison = 64,
        /// <summary>
        /// 8=展会
        /// </summary>
        Exhibition = 128,
        /// <summary>
        /// 9=催稿
        /// </summary>
        Manuscript = 256,
        /// <summary>
        /// 10=超市
        /// </summary>
        Supermarket = 512,
        /// <summary>
        /// 11=果蔬店
        /// </summary>
        FruitShop = 1024,
        /// <summary>
        /// 12=布料店
        /// </summary>
        FabricStore = 2048,
        /// <summary>
        /// 13=情趣用品店
        /// </summary>
        SexToyStore = 4096,
        /// <summary>
        /// 14=钓鱼
        /// </summary>
        Fishing = 8192,
        /// <summary>
        /// 15=鱼饵购买
        /// </summary>
        FishingBaitShop = 16384,
        /// <summary>
        /// 16=摄影
        /// </summary>
        Photography = 32768,
        /// <summary>
        /// 17=咖啡店
        /// </summary>
        CoffeeShop = 65535,
        /// <summary>
        /// 18=酒吧
        /// </summary>
        Bar = 131072,
    }

} 

