
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class GameSceneData : Luban.BeanBase
{
    public GameSceneData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        SceneName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("SceneName"));
        Desc = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Desc"));
        ScenePath = (string)_obj.GetValue("ScenePath");
        ReturnScene = (long)_obj.GetValue("ReturnScene");
        SceneImage = (string)_obj.GetValue("SceneImage");
        PermanentScene = (PermanentSceneType)(int)_obj.GetValue("PermanentScene");
        { var __json0 = _obj.GetValue("ActiveNpcID"); ActiveNpcID = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  ActiveNpcID.Add(__v0); }   }
    }

    public static GameSceneData DeserializeGameSceneData(JToken _buf)
    {
        return new GameSceneData(_buf);
    }

    /// <summary>
    /// 场景唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly TbLocalzationKeyData SceneName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly TbLocalzationKeyData Desc;
    /// <summary>
    /// 场景路径
    /// </summary>
    public readonly string ScenePath;
    /// <summary>
    /// 返回场景
    /// </summary>
    public readonly long ReturnScene;
    /// <summary>
    /// 场景图片
    /// </summary>
    public readonly string SceneImage;
    /// <summary>
    /// 常驻场景
    /// </summary>
    public readonly PermanentSceneType PermanentScene;
    /// <summary>
    /// 活动的NPC列表
    /// </summary>
    public readonly System.Collections.Generic.List<long> ActiveNpcID;


    public const int __ID__ = -1249990044;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SceneName?.ResolveRef(tables);
        Desc?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "SceneName:" + SceneName + ","
        + "Desc:" + Desc + ","
        + "ScenePath:" + ScenePath + ","
        + "ReturnScene:" + ReturnScene + ","
        + "SceneImage:" + SceneImage + ","
        + "PermanentScene:" + PermanentScene + ","
        + "ActiveNpcID:" + Luban.StringUtil.CollectionToString(ActiveNpcID) + ","
        + "}";
    }
}
}

