
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class GiftItemData : Luban.BeanBase
{
    public GiftItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        Goodwill = (int)_obj.GetValue("Goodwill");
        { var __json0 = _obj.GetValue("RewardProp"); RewardProp = new System.Collections.Generic.List<TbRewardPropData>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbRewardPropData __v0;  __v0 = global::XFramework.TbRewardPropData.DeserializeTbRewardPropData(__e0);  RewardProp.Add(__v0); }   }
    }

    public static GiftItemData DeserializeGiftItemData(JToken _buf)
    {
        return new GiftItemData(_buf);
    }

    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 好感度
    /// </summary>
    public readonly int Goodwill;
    /// <summary>
    /// 获得属性(灵感/压力)
    /// </summary>
    public readonly System.Collections.Generic.List<TbRewardPropData> RewardProp;


    public const int __ID__ = 39456461;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardProp) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "Goodwill:" + Goodwill + ","
        + "RewardProp:" + Luban.StringUtil.CollectionToString(RewardProp) + ","
        + "}";
    }
}
}

