
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemType
    {
        /// <summary>
        /// 固定无变化材料
        /// </summary>
        Material = 0,
        /// <summary>
        /// 固定可以使用的道具
        /// </summary>
        Consumables = 1,
        /// <summary>
        /// 动态材料
        /// </summary>
        Runtime = 2,
        /// <summary>
        /// 催稿玩法：女主创作产出的线稿
        /// </summary>
        Manuscript = 3,
    }

} 

