
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemMaterialType
    {
        /// <summary>
        /// 配方道具
        /// </summary>
        Recipe = 1,
        /// <summary>
        /// 手办模型/模具框架
        /// </summary>
        FigureModel = 2,
        /// <summary>
        /// 绘画贴纸（女主产出）
        /// </summary>
        Painting = 3,
        /// <summary>
        /// 工厂生产资料（框架+贴纸合成产物）
        /// </summary>
        FactoryProductionMaterials = 4,
        /// <summary>
        /// 周边货物
        /// </summary>
        Merchandise = 5,
        /// <summary>
        /// 娃娃
        /// </summary>
        Doll = 6,
        /// <summary>
        /// 食材道具
        /// </summary>
        Ingredient = 7,
    }

} 

