
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 好感道具
        /// </summary>
        Affection = 1,
        /// <summary>
        /// 灵感道具
        /// </summary>
        Inspiration = 2,
        /// <summary>
        /// 压力道具
        /// </summary>
        Stress = 3,
        /// <summary>
        /// 体力道具
        /// </summary>
        Stamina = 4,
        /// <summary>
        /// 剧情道具
        /// </summary>
        Story = 5,
        /// <summary>
        /// 食材道具
        /// </summary>
        Ingredient = 6,
        /// <summary>
        /// 配方道具
        /// </summary>
        Recipe = 7,
        /// <summary>
        /// 食物道具
        /// </summary>
        Food = 8,
        /// <summary>
        /// 手办模型
        /// </summary>
        FigureModel = 9,
        /// <summary>
        /// 绘画道具
        /// </summary>
        Painting = 10,
        /// <summary>
        /// 工厂生产材料
        /// </summary>
        FactoryProductionMaterials = 11,
        /// <summary>
        /// 布料
        /// </summary>
        Cloth = 12,
        /// <summary>
        /// 周边货物
        /// </summary>
        Merchandise = 13,
        /// <summary>
        /// 商店道具
        /// </summary>
        ShopItem = 14,
        /// <summary>
        /// 鱼饵店
        /// </summary>
        FishBait = 15,
        /// <summary>
        /// 鱼竿
        /// </summary>
        FishRod = 16,
        /// <summary>
        /// 情趣道具
        /// </summary>
        AdultToy = 17,
        /// <summary>
        /// 娃娃机
        /// </summary>
        ClawMachineDoll = 18,
    }

} 

