
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemConsumType
    {
        /// <summary>
        /// 食材道具
        /// </summary>
        Ingredient = 1,
        /// <summary>
        /// 食物道具
        /// </summary>
        Food = 2,
    }

} 

