
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ItemMaterialType
    {
        /// <summary>
        /// 默认材料类型
        /// </summary>
        None = 0,
        /// <summary>
        /// 配方道具
        /// </summary>
        Recipe = 1,
        /// <summary>
        /// 手办模型/模具框架
        /// </summary>
        FigureModel = 2,
        /// <summary>
        /// 绘画贴纸（女主产出）
        /// </summary>
        Painting = 3,
        /// <summary>
        /// 工厂生产资料（框架+贴纸合成产物）
        /// </summary>
        FactoryProductionMaterials = 4,
        /// <summary>
        /// 周边货物
        /// </summary>
        Merchandise = 5,
        /// <summary>
        /// 娃娃
        /// </summary>
        Doll = 6,
        /// <summary>
        /// 食材
        /// </summary>
        Ingredient = 7,
        /// <summary>
        /// 布料
        /// </summary>
        Cloth = 8,
        /// <summary>
        /// 渔具
        /// </summary>
        FishingGear = 9,
        /// <summary>
        /// 鱼饵
        /// </summary>
        FishingBait = 10,
        /// <summary>
        /// 情趣用品
        /// </summary>
        AdultProduct = 11,
        /// <summary>
        /// 商店特殊道具
        /// </summary>
        ShopSpecialItem = 12,
        /// <summary>
        /// 钓鱼产品
        /// </summary>
        FishingProduct = 13,
        /// <summary>
        /// 鱼
        /// </summary>
        Fishing = 14,
    }

} 

