
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ItemData : Luban.BeanBase
{
    public ItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        IconName = (string)_obj.GetValue("iconName");
        NameKey = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("NameKey"));
        DescKey = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("DescKey"));
        ItemType = (ItemType)(int)_obj.GetValue("ItemType");
        MaxNum = (int)_obj.GetValue("MaxNum");
        Quality = (ItemQuality)(int)_obj.GetValue("Quality");
        Shop = global::XFramework.TbRewardPropData.DeserializeTbRewardPropData(_obj.GetValue("Shop"));
    }

    public static ItemData DeserializeItemData(JToken _buf)
    {
        return new ItemData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 物品图标
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly TbLocalzationKeyData NameKey;
    public readonly TbLocalzationKeyData DescKey;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly ItemType ItemType;
    /// <summary>
    /// 堆叠上限
    /// </summary>
    public readonly int MaxNum;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly ItemQuality Quality;
    /// <summary>
    /// 出售价格
    /// </summary>
    public readonly TbRewardPropData Shop;


    public const int __ID__ = 1241678205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NameKey?.ResolveRef(tables);
        DescKey?.ResolveRef(tables);
        Shop?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "iconName:" + IconName + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "ItemType:" + ItemType + ","
        + "MaxNum:" + MaxNum + ","
        + "Quality:" + Quality + ","
        + "Shop:" + Shop + ","
        + "}";
    }
}
}

