
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class ManuscriptItemData : Luban.BeanBase
{
    public ManuscriptItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        DraftImageName = (string)_obj.GetValue("DraftImageName");
        BaseScore = (int)_obj.GetValue("BaseScore");
        Prob30 = (float)_obj.GetValue("Prob30");
        Prob50 = (float)_obj.GetValue("Prob50");
        Prob100 = (float)_obj.GetValue("Prob100");
        IsSpecial = (bool)_obj.GetValue("IsSpecial");
        FinalImageName = (string)_obj.GetValue("FinalImageName");
    }

    public static ManuscriptItemData DeserializeManuscriptItemData(JToken _buf)
    {
        return new ManuscriptItemData(_buf);
    }

    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 草稿图
    /// </summary>
    public readonly string DraftImageName;
    /// <summary>
    /// 线稿基础评分
    /// </summary>
    public readonly int BaseScore;
    /// <summary>
    /// 30灵感单张抽取概率(0~1)
    /// </summary>
    public readonly float Prob30;
    /// <summary>
    /// 50灵感单张抽取概率(0~1)
    /// </summary>
    public readonly float Prob50;
    /// <summary>
    /// 100灵感单张抽取概率(0~1)
    /// </summary>
    public readonly float Prob100;
    /// <summary>
    /// 是否是特殊稿件
    /// </summary>
    public readonly bool IsSpecial;
    /// <summary>
    /// 成品图
    /// </summary>
    public readonly string FinalImageName;


    public const int __ID__ = 965697155;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "DraftImageName:" + DraftImageName + ","
        + "BaseScore:" + BaseScore + ","
        + "Prob30:" + Prob30 + ","
        + "Prob50:" + Prob50 + ","
        + "Prob100:" + Prob100 + ","
        + "IsSpecial:" + IsSpecial + ","
        + "FinalImageName:" + FinalImageName + ","
        + "}";
    }
}
}

