
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class MaterialItemData : Luban.BeanBase
{
    public MaterialItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        MaterialType = (ItemMaterialType)(int)_obj.GetValue("MaterialType");
    }

    public static MaterialItemData DeserializeMaterialItemData(JToken _buf)
    {
        return new MaterialItemData(_buf);
    }

    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 材料类别
    /// </summary>
    public readonly ItemMaterialType MaterialType;


    public const int __ID__ = 1020400580;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "MaterialType:" + MaterialType + ","
        + "}";
    }
}
}

