
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class NpcData : Luban.BeanBase
{
    public NpcData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        SceneSpinePath = (string)_obj.GetValue("SceneSpinePath");
        MiniImg = (string)_obj.GetValue("MiniImg");
    }

    public static NpcData DeserializeNpcData(JToken _buf)
    {
        return new NpcData(_buf);
    }

    /// <summary>
    /// 备注
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly TbLocalzationKeyData Name;
    /// <summary>
    /// 立绘(后期换为Spine)
    /// </summary>
    public readonly string SceneSpinePath;
    /// <summary>
    /// 立绘
    /// </summary>
    public readonly string MiniImg;


    public const int __ID__ = -489140725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "Name:" + Name + ","
        + "SceneSpinePath:" + SceneSpinePath + ","
        + "MiniImg:" + MiniImg + ","
        + "}";
    }
}
}

