
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class NpcData : Luban.BeanBase
{
    public NpcData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        CharacterData = (long)_obj.GetValue("CharacterData");
        SceneSpinePath = (string)_obj.GetValue("SceneSpinePath");
        MiniImg = (string)_obj.GetValue("MiniImg");
        FunctionType = (FunctionGroup)(int)_obj.GetValue("FunctionType");
        { var __json0 = _obj.GetValue("PointerDialogue"); PointerDialogue = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PointerDialogue.Add(__v0); }   }
        { var __json0 = _obj.GetValue("DailyDialogue"); DailyDialogue = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  DailyDialogue.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PlotDialogue"); PlotDialogue = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PlotDialogue.Add(__v0); }   }
        WeekType = (ShowRuleWeekType)(int)_obj.GetValue("WeekType");
        AppearanceTime = (ShowRuleTimeType)(int)_obj.GetValue("AppearanceTime");
        ScenePosition = global::XFramework.vector2.Deserializevector2(_obj.GetValue("ScenePosition"));
    }

    public static NpcData DeserializeNpcData(JToken _buf)
    {
        return new NpcData(_buf);
    }

    /// <summary>
    /// 备注
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly TbLocalzationKeyData Name;
    /// <summary>
    /// 绑定真实ID
    /// </summary>
    public readonly long CharacterData;
    /// <summary>
    /// 立绘(后期换为Spine)
    /// </summary>
    public readonly string SceneSpinePath;
    /// <summary>
    /// 立绘
    /// </summary>
    public readonly string MiniImg;
    /// <summary>
    /// 功能组
    /// </summary>
    public readonly FunctionGroup FunctionType;
    /// <summary>
    /// 点击对话
    /// </summary>
    public readonly System.Collections.Generic.List<long> PointerDialogue;
    /// <summary>
    /// 日常对话
    /// </summary>
    public readonly System.Collections.Generic.List<long> DailyDialogue;
    /// <summary>
    /// 剧情对话
    /// </summary>
    public readonly System.Collections.Generic.List<long> PlotDialogue;
    /// <summary>
    /// 出现周天
    /// </summary>
    public readonly ShowRuleWeekType WeekType;
    /// <summary>
    /// 出现时间段
    /// </summary>
    public readonly ShowRuleTimeType AppearanceTime;
    /// <summary>
    /// 出现位置
    /// </summary>
    public readonly vector2 ScenePosition;


    public const int __ID__ = -489140725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "Name:" + Name + ","
        + "CharacterData:" + CharacterData + ","
        + "SceneSpinePath:" + SceneSpinePath + ","
        + "MiniImg:" + MiniImg + ","
        + "FunctionType:" + FunctionType + ","
        + "PointerDialogue:" + Luban.StringUtil.CollectionToString(PointerDialogue) + ","
        + "DailyDialogue:" + Luban.StringUtil.CollectionToString(DailyDialogue) + ","
        + "PlotDialogue:" + Luban.StringUtil.CollectionToString(PlotDialogue) + ","
        + "WeekType:" + WeekType + ","
        + "AppearanceTime:" + AppearanceTime + ","
        + "ScenePosition:" + ScenePosition + ","
        + "}";
    }
}
}

