
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class NpcSpawnGroupData : Luban.BeanBase
{
    public NpcSpawnGroupData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        SelectMode = (SelectMode)(int)_obj.GetValue("SelectMode");
        SelectCount = (int)_obj.GetValue("SelectCount");
        RefreshType = (RefreshType)(int)_obj.GetValue("RefreshType");
    }

    public static NpcSpawnGroupData DeserializeNpcSpawnGroupData(JToken _buf)
    {
        return new NpcSpawnGroupData(_buf);
    }

    /// <summary>
    /// 表ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 随机模式
    /// </summary>
    public readonly SelectMode SelectMode;
    /// <summary>
    /// 抽几个
    /// </summary>
    public readonly int SelectCount;
    /// <summary>
    /// 刷新模式
    /// </summary>
    public readonly RefreshType RefreshType;


    public const int __ID__ = -824474961;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "SelectMode:" + SelectMode + ","
        + "SelectCount:" + SelectCount + ","
        + "RefreshType:" + RefreshType + ","
        + "}";
    }
}
}

