
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class NpcSpawnRuleData : Luban.BeanBase
{
    public NpcSpawnRuleData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        GroupID = (long)_obj.GetValue("GroupID");
        NpcID = (long)_obj.GetValue("NpcID");
        FavorRange = global::XFramework.vector2.Deserializevector2(_obj.GetValue("FavorRange"));
        FeelingRange = global::XFramework.vector2.Deserializevector2(_obj.GetValue("FeelingRange"));
        Priority = (int)_obj.GetValue("Priority");
    }

    public static NpcSpawnRuleData DeserializeNpcSpawnRuleData(JToken _buf)
    {
        return new NpcSpawnRuleData(_buf);
    }

    /// <summary>
    /// 表ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 组ID
    /// </summary>
    public readonly long GroupID;
    /// <summary>
    /// 对应表现表ID
    /// </summary>
    public readonly long NpcID;
    /// <summary>
    /// 好感度
    /// </summary>
    public readonly vector2 FavorRange;
    /// <summary>
    /// 心情值
    /// </summary>
    public readonly vector2 FeelingRange;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;


    public const int __ID__ = -185595872;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "GroupID:" + GroupID + ","
        + "NpcID:" + NpcID + ","
        + "FavorRange:" + FavorRange + ","
        + "FeelingRange:" + FeelingRange + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

