
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum PaintTubeColorType
    {
        /// <summary>
        /// 白色
        /// </summary>
        White = 0,
        /// <summary>
        /// 黑色
        /// </summary>
        Black = 1,
        /// <summary>
        /// 红色
        /// </summary>
        Red = 2,
        /// <summary>
        /// 黄色
        /// </summary>
        Yellow = 3,
        /// <summary>
        /// 蓝色
        /// </summary>
        Blue = 4,
        /// <summary>
        /// 绿色
        /// </summary>
        Green = 5,
        /// <summary>
        /// 紫色
        /// </summary>
        Purple = 6,
    }

} 

