
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class PopularityData : Luban.BeanBase
{
    public PopularityData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        Value = (int)_obj.GetValue("Value");
    }

    public static PopularityData DeserializePopularityData(JToken _buf)
    {
        return new PopularityData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 唯一名字
    /// </summary>
    public readonly TbLocalzationKeyData Name;
    /// <summary>
    /// 粉丝数
    /// </summary>
    public readonly int Value;


    public const int __ID__ = 1756797087;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

