
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class PriavateMessageData : Luban.BeanBase
{
    public PriavateMessageData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        FenName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("FenName"));
        Desc = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Desc"));
        { var __json0 = _obj.GetValue("Option"); Option = new System.Collections.Generic.List<TbLocalzationKeyData>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbLocalzationKeyData __v0;  __v0 = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(__e0);  Option.Add(__v0); }   }
        { var __json0 = _obj.GetValue("RewardID"); RewardID = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  RewardID.Add(__v0); }   }
    }

    public static PriavateMessageData DeserializePriavateMessageData(JToken _buf)
    {
        return new PriavateMessageData(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 粉丝名称
    /// </summary>
    public readonly TbLocalzationKeyData FenName;
    /// <summary>
    /// 正文内容
    /// </summary>
    public readonly TbLocalzationKeyData Desc;
    /// <summary>
    /// 回复选项
    /// </summary>
    public readonly System.Collections.Generic.List<TbLocalzationKeyData> Option;
    /// <summary>
    /// 奖励表ID
    /// </summary>
    public readonly System.Collections.Generic.List<long> RewardID;


    public const int __ID__ = -1474322853;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        FenName?.ResolveRef(tables);
        Desc?.ResolveRef(tables);
        foreach (var _e in Option) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "FenName:" + FenName + ","
        + "Desc:" + Desc + ","
        + "Option:" + Luban.StringUtil.CollectionToString(Option) + ","
        + "RewardID:" + Luban.StringUtil.CollectionToString(RewardID) + ","
        + "}";
    }
}
}

