
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum PropertyType
    {
        /// <summary>
        /// 通用游戏货币
        /// </summary>
        Gold = 1,
        /// <summary>
        /// 游戏玩法货币
        /// </summary>
        GameGold = 2,
        /// <summary>
        /// 体力值
        /// </summary>
        Strength = 3,
        /// <summary>
        /// 行动值
        /// </summary>
        ActionPointsValue = 4,
    }

} 

