
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class PropertyData : Luban.BeanBase
{
    public PropertyData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Property = (PropertyType)(int)_obj.GetValue("Property");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        Remark = (string)_obj.GetValue("Remark");
        DeftualNumber = (int)_obj.GetValue("DeftualNumber");
        NumberLimit = (int)_obj.GetValue("NumberLimit");
    }

    public static PropertyData DeserializePropertyData(JToken _buf)
    {
        return new PropertyData(_buf);
    }

    /// <summary>
    /// 属性
    /// </summary>
    public readonly PropertyType Property;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly TbLocalzationKeyData Name;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 默认值
    /// </summary>
    public readonly int DeftualNumber;
    /// <summary>
    /// 最大值
    /// </summary>
    public readonly int NumberLimit;


    public const int __ID__ = -700669121;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Property:" + Property + ","
        + "Name:" + Name + ","
        + "Remark:" + Remark + ","
        + "DeftualNumber:" + DeftualNumber + ","
        + "NumberLimit:" + NumberLimit + ","
        + "}";
    }
}
}

