
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum PropertyType
    {
        /// <summary>
        /// 通用游戏货币
        /// </summary>
        Coin = 1,
        /// <summary>
        /// 游戏玩法货币
        /// </summary>
        GameCoin = 2,
        /// <summary>
        /// 体力值
        /// </summary>
        Strength = 3,
        /// <summary>
        /// 行动值
        /// </summary>
        ActionPointsValue = 4,
        /// <summary>
        /// 基本生产量
        /// </summary>
        BasicProductionVolume = 5,
        /// <summary>
        /// 基础良品率
        /// </summary>
        BasicGoodProductRate = 6,
        /// <summary>
        /// 娃娃机游戏次数
        /// </summary>
        ClawMachineValue = 7,
        /// <summary>
        /// 爱心币
        /// </summary>
        HeartCoins = 8,
        /// <summary>
        /// 粉丝数
        /// </summary>
        FenCount = 9,
        /// <summary>
        /// 粉丝增长系数
        /// </summary>
        FanGrowthRate = 10,
        /// <summary>
        /// 体力百分比
        /// </summary>
        StaminaPercent = 11,
        /// <summary>
        /// 体力上限
        /// </summary>
        StaminaMax = 12,
    }

} 

