
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestDataConfig : Luban.BeanBase
{
    public QuestDataConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        AcceptTrigger = (string)_obj.GetValue("AcceptTrigger");
        AcceptCond = (long)_obj.GetValue("AcceptCond");
        NameKey = (string)_obj.GetValue("NameKey");
        DescKey = (string)_obj.GetValue("DescKey");
        QuestObjData = (string)_obj.GetValue("QuestObjData");
        ExtraQuestObjData = (string)_obj.GetValue("ExtraQuestObjData");
        Reward = (string)_obj.GetValue("Reward");
        ExtraReward = (string)_obj.GetValue("ExtraReward");
    }

    public static QuestDataConfig DeserializeQuestDataConfig(JToken _buf)
    {
        return new QuestDataConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 领取触发 类型:参数:参数，多条用 / 分隔
    /// </summary>
    public readonly string AcceptTrigger;
    /// <summary>
    /// 领取条件ID
    /// </summary>
    public readonly long AcceptCond;
    /// <summary>
    /// 任务名称
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 任务文本
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 任务目标 类型:参数:参数，多条用 / 分隔
    /// </summary>
    public readonly string QuestObjData;
    /// <summary>
    /// 超额目标 类型:参数:参数，多条用 / 分隔
    /// </summary>
    public readonly string ExtraQuestObjData;
    /// <summary>
    /// 奖励 Item:道具ID[:数量] / 属性名:数值 / 角色属性名:NPC ID:数值，多条用 / 分隔
    /// </summary>
    public readonly string Reward;
    /// <summary>
    /// 超额奖励 写法同奖励列
    /// </summary>
    public readonly string ExtraReward;


    public const int __ID__ = 1447227886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "AcceptTrigger:" + AcceptTrigger + ","
        + "AcceptCond:" + AcceptCond + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "QuestObjData:" + QuestObjData + ","
        + "ExtraQuestObjData:" + ExtraQuestObjData + ","
        + "Reward:" + Reward + ","
        + "ExtraReward:" + ExtraReward + ","
        + "}";
    }
}
}

