
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestDataConfig : Luban.BeanBase
{
    public QuestDataConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        QuestTrigger = (string)_obj.GetValue("QuestTrigger");
        AcceptCond = (long)_obj.GetValue("AcceptCond");
        NameKey = (string)_obj.GetValue("NameKey");
        DescKey = (string)_obj.GetValue("DescKey");
        IconKey = (string)_obj.GetValue("IconKey");
        { var __json0 = _obj.GetValue("QuestObjData"); QuestObjData = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  QuestObjData.Add(__v0); }   }
        Reward = (string)_obj.GetValue("Reward");
        ObjInOrder = (bool)_obj.GetValue("ObjInOrder");
    }

    public static QuestDataConfig DeserializeQuestDataConfig(JToken _buf)
    {
        return new QuestDataConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 领取方式
    /// </summary>
    public readonly string QuestTrigger;
    /// <summary>
    /// 接受条件
    /// </summary>
    public readonly long AcceptCond;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 文本
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string IconKey;
    /// <summary>
    /// 任务目标
    /// </summary>
    public readonly System.Collections.Generic.List<long> QuestObjData;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly string Reward;
    /// <summary>
    /// 目标是否按顺序完成
    /// </summary>
    public readonly bool ObjInOrder;


    public const int __ID__ = 1447227886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "QuestTrigger:" + QuestTrigger + ","
        + "AcceptCond:" + AcceptCond + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "IconKey:" + IconKey + ","
        + "QuestObjData:" + Luban.StringUtil.CollectionToString(QuestObjData) + ","
        + "Reward:" + Reward + ","
        + "ObjInOrder:" + ObjInOrder + ","
        + "}";
    }
}
}

