
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestRewardData : Luban.BeanBase
{
    public QuestRewardData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        NameKey = (string)_obj.GetValue("NameKey");
        IconKey = (string)_obj.GetValue("IconKey");
    }

    public static QuestRewardData DeserializeQuestRewardData(JToken _buf)
    {
        return new QuestRewardData(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string IconKey;


    public const int __ID__ = -1971192357;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "NameKey:" + NameKey + ","
        + "IconKey:" + IconKey + ","
        + "}";
    }
}
}

