
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestObjConfig : Luban.BeanBase
{
    public QuestObjConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        DescKey = (string)_obj.GetValue("DescKey");
        QuestObjData = (string)_obj.GetValue("QuestObjData");
        Reward = (string)_obj.GetValue("Reward");
        ExtraDescKey = (string)_obj.GetValue("ExtraDescKey");
        ExtraCompleteCond = (string)_obj.GetValue("ExtraCompleteCond");
        ExtraReward = (string)_obj.GetValue("ExtraReward");
    }

    public static QuestObjConfig DeserializeQuestObjConfig(JToken _buf)
    {
        return new QuestObjConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 描述文本
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 任务目标
    /// </summary>
    public readonly string QuestObjData;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly string Reward;
    /// <summary>
    /// 超额条件描述文本（可选）
    /// </summary>
    public readonly string ExtraDescKey;
    /// <summary>
    /// 任务超额完成条件（可选）
    /// </summary>
    public readonly string ExtraCompleteCond;
    /// <summary>
    /// 超额完成奖励
    /// </summary>
    public readonly string ExtraReward;


    public const int __ID__ = -76351369;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "DescKey:" + DescKey + ","
        + "QuestObjData:" + QuestObjData + ","
        + "Reward:" + Reward + ","
        + "ExtraDescKey:" + ExtraDescKey + ","
        + "ExtraCompleteCond:" + ExtraCompleteCond + ","
        + "ExtraReward:" + ExtraReward + ","
        + "}";
    }
}
}

