
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestStoryCondData : Luban.BeanBase
{
    public QuestStoryCondData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        { var __json0 = _obj.GetValue("ItemOwn"); ItemOwn = new System.Collections.Generic.List<TbUlocakItemData>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbUlocakItemData __v0;  __v0 = global::XFramework.TbUlocakItemData.DeserializeTbUlocakItemData(__e0);  ItemOwn.Add(__v0); }   }
        { var __json0 = _obj.GetValue("NpcProp"); NpcProp = new System.Collections.Generic.List<TbUlockCharacterData>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { TbUlockCharacterData __v0;  __v0 = global::XFramework.TbUlockCharacterData.DeserializeTbUlockCharacterData(__e0);  NpcProp.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PlotPre"); PlotPre = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  PlotPre.Add(__v0); }   }
        { var __json0 = _obj.GetValue("DlgPre"); DlgPre = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  DlgPre.Add(__v0); }   }
        Day = (int)_obj.GetValue("Day");
        TimeSlot = (ShowRuleTimeType)(int)_obj.GetValue("TimeSlot");
        { var __json0 = _obj.GetValue("QuestPre"); QuestPre = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  QuestPre.Add(__v0); }   }
        { var __json0 = _obj.GetValue("Satisfy"); Satisfy = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  Satisfy.Add(__v0); }   }
        { var __json0 = _obj.GetValue("NotSatisfy"); NotSatisfy = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  NotSatisfy.Add(__v0); }   }
        GameScore = (string)_obj.GetValue("GameScore");
    }

    public static QuestStoryCondData DeserializeQuestStoryCondData(JToken _buf)
    {
        return new QuestStoryCondData(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 道具持有(道具ID+数量)
    /// </summary>
    public readonly System.Collections.Generic.List<TbUlocakItemData> ItemOwn;
    /// <summary>
    /// NPC数值达标(角色ID+属性+数值)
    /// </summary>
    public readonly System.Collections.Generic.List<TbUlockCharacterData> NpcProp;
    /// <summary>
    /// 剧情前置
    /// </summary>
    public readonly System.Collections.Generic.List<long> PlotPre;
    /// <summary>
    /// 对话前置
    /// </summary>
    public readonly System.Collections.Generic.List<long> DlgPre;
    /// <summary>
    /// 天数达到(0=不限)
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 时间段(不限填All)
    /// </summary>
    public readonly ShowRuleTimeType TimeSlot;
    /// <summary>
    /// 前置完成任务
    /// </summary>
    public readonly System.Collections.Generic.List<long> QuestPre;
    /// <summary>
    /// 满足走向（暂不实现）
    /// </summary>
    public readonly System.Collections.Generic.List<long> Satisfy;
    /// <summary>
    /// 不满足走向（暂不实现）
    /// </summary>
    public readonly System.Collections.Generic.List<long> NotSatisfy;
    /// <summary>
    /// 游戏评分（暂不实现）
    /// </summary>
    public readonly string GameScore;


    public const int __ID__ = -491709345;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ItemOwn) { _e?.ResolveRef(tables); }
        foreach (var _e in NpcProp) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "ItemOwn:" + Luban.StringUtil.CollectionToString(ItemOwn) + ","
        + "NpcProp:" + Luban.StringUtil.CollectionToString(NpcProp) + ","
        + "PlotPre:" + Luban.StringUtil.CollectionToString(PlotPre) + ","
        + "DlgPre:" + Luban.StringUtil.CollectionToString(DlgPre) + ","
        + "Day:" + Day + ","
        + "TimeSlot:" + TimeSlot + ","
        + "QuestPre:" + Luban.StringUtil.CollectionToString(QuestPre) + ","
        + "Satisfy:" + Luban.StringUtil.CollectionToString(Satisfy) + ","
        + "NotSatisfy:" + Luban.StringUtil.CollectionToString(NotSatisfy) + ","
        + "GameScore:" + GameScore + ","
        + "}";
    }
}
}

