
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class QuestCategoryData : Luban.BeanBase
{
    public QuestCategoryData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (long)_obj.GetValue("Id");
        Remark = (string)_obj.GetValue("Remark");
        NameKey = (string)_obj.GetValue("NameKey");
        DescKey = (string)_obj.GetValue("DescKey");
        IconKey = (string)_obj.GetValue("IconKey");
        { var __json0 = _obj.GetValue("QuestId"); QuestId = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  QuestId.Add(__v0); }   }
        Reward = (string)_obj.GetValue("Reward");
    }

    public static QuestCategoryData DeserializeQuestCategoryData(JToken _buf)
    {
        return new QuestCategoryData(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly long Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string IconKey;
    /// <summary>
    /// 任务Id
    /// </summary>
    public readonly System.Collections.Generic.List<long> QuestId;
    /// <summary>
    /// 任务类别奖励
    /// </summary>
    public readonly string Reward;


    public const int __ID__ = -1104749654;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remark:" + Remark + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "IconKey:" + IconKey + ","
        + "QuestId:" + Luban.StringUtil.CollectionToString(QuestId) + ","
        + "Reward:" + Reward + ","
        + "}";
    }
}
}

