
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum QuestObjType
    {
        /// <summary>
        /// 未设置
        /// </summary>
        None = 0,
        /// <summary>
        /// DayPassed:天数
        /// </summary>
        DayPassed = 1,
        /// <summary>
        /// Dialog:对话ID
        /// </summary>
        Dialog = 2,
        /// <summary>
        /// CompleteQuest:任务ID
        /// </summary>
        CompleteQuest = 3,
        /// <summary>
        /// HoldItem:道具ID[:数量]
        /// </summary>
        HoldItem = 4,
        /// <summary>
        /// NpcProp:NPC ID:数值[:属性类型]，属性类型默认 Goodwill
        /// </summary>
        NpcProp = 5,
        /// <summary>
        /// CompleteGame:游戏ID:局数[:结果 1胜/2负]
        /// </summary>
        CompleteGame = 6,
        /// <summary>
        /// DialogNpc:NPC ID[:次数]
        /// </summary>
        DialogNpc = 7,
        /// <summary>
        /// DialogNpcWithItem:NPC ID:道具ID[:次数]，每次消耗 1 个道具
        /// </summary>
        DialogNpcWithItem = 8,
        /// <summary>
        /// GiveGift:NPC ID:礼物ID[:次数]，礼物ID 填 0 为任意礼物
        /// </summary>
        GiveGift = 9,
        /// <summary>
        /// BuyItem:道具ID[:件数]，道具ID 填 0 为任意道具
        /// </summary>
        BuyItem = 10,
    }

} 

