
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class RecipeItemData : Luban.BeanBase
{
    public RecipeItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Remark = (string)_obj.GetValue("Remark");
        { var __json0 = _obj.GetValue("TypeNum"); TypeNum = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  TypeNum.Add(__v0); }   }
        Synthesis = (long)_obj.GetValue("Synthesis");
    }

    public static RecipeItemData DeserializeRecipeItemData(JToken _buf)
    {
        return new RecipeItemData(_buf);
    }

    /// <summary>
    /// 物品表ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 对应数值
    /// </summary>
    public readonly System.Collections.Generic.List<long> TypeNum;
    /// <summary>
    /// 合成
    /// </summary>
    public readonly long Synthesis;


    public const int __ID__ = 660616491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Remark:" + Remark + ","
        + "TypeNum:" + Luban.StringUtil.CollectionToString(TypeNum) + ","
        + "Synthesis:" + Synthesis + ","
        + "}";
    }
}
}

