
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum ShopUpdateType
    {
        /// <summary>
        /// 每天刷新
        /// </summary>
        Day = 0,
        /// <summary>
        /// 每周刷新
        /// </summary>
        Week = 1,
    }

} 

