
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    [System.Flags]
    public enum ShowRuleTimeType
    {
        /// <summary>
        /// 早上
        /// </summary>
        Morning = 1,
        /// <summary>
        /// 中午时间段
        /// </summary>
        Noon = 2,
        /// <summary>
        /// 黄昏时间段
        /// </summary>
        Evening = 4,
        /// <summary>
        /// 夜晚时间段
        /// </summary>
        Midnight = 8,
        /// <summary>
        /// 全部时间段
        /// </summary>
        All = 15,
    }

} 

