
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace XFramework
{
public partial class Tables
{
    /// <summary>
    /// 游戏对话配置数据
    /// </summary>
    public TbDialogueData TbDialogueData {get; }
    /// <summary>
    /// NPC配置表
    /// </summary>
    public TbNpcData TbNpcData {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbDialogueData = new TbDialogueData(loader("tbdialoguedata"));
        TbNpcData = new TbNpcData(loader("tbnpcdata"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbDialogueData.ResolveRef(this);
        TbNpcData.ResolveRef(this);
    }
}

}

