
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace XFramework
{
public partial class Tables
{
    /// <summary>
    /// 游戏对话配置数据
    /// </summary>
    public TbDialogueData TbDialogueData {get; }
    /// <summary>
    /// NPC配置表
    /// </summary>
    public TbNpcData TbNpcData {get; }
    /// <summary>
    /// 布料商店配置表
    /// </summary>
    public TbClothShopData TbClothShopData {get; }
    /// <summary>
    /// 属性配置表
    /// </summary>
    public TbPropertyData TbPropertyData {get; }
    /// <summary>
    /// UI界面配置表
    /// </summary>
    public TbUIPageData TbUIPageData {get; }
    /// <summary>
    /// 角色配置表
    /// </summary>
    public TbCharacterData TbCharacterData {get; }
    /// <summary>
    /// 超市商店数据
    /// </summary>
    public TbSuperMarketShopData TbSuperMarketShopData {get; }
    /// <summary>
    /// 场景配置表
    /// </summary>
    public TbGameSceneData TbGameSceneData {get; }
    /// <summary>
    /// 世界地图配置表
    /// </summary>
    public TbWordMapSceneData TbWordMapSceneData {get; }
    /// <summary>
    /// 果蔬店配置表
    /// </summary>
    public TbFruitShopData TbFruitShopData {get; }
    /// <summary>
    /// 情趣用品店配置表
    /// </summary>
    public TbSexToShopData TbSexToShopData {get; }
    /// <summary>
    /// 钓鱼商店
    /// </summary>
    public TbFishShopData TbFishShopData {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbDialogueData = new TbDialogueData(loader("tbdialoguedata"));
        TbNpcData = new TbNpcData(loader("tbnpcdata"));
        TbClothShopData = new TbClothShopData(loader("tbclothshopdata"));
        TbPropertyData = new TbPropertyData(loader("tbpropertydata"));
        TbUIPageData = new TbUIPageData(loader("tbuipagedata"));
        TbCharacterData = new TbCharacterData(loader("tbcharacterdata"));
        TbSuperMarketShopData = new TbSuperMarketShopData(loader("tbsupermarketshopdata"));
        TbGameSceneData = new TbGameSceneData(loader("tbgamescenedata"));
        TbWordMapSceneData = new TbWordMapSceneData(loader("tbwordmapscenedata"));
        TbFruitShopData = new TbFruitShopData(loader("tbfruitshopdata"));
        TbSexToShopData = new TbSexToShopData(loader("tbsextoshopdata"));
        TbFishShopData = new TbFishShopData(loader("tbfishshopdata"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbDialogueData.ResolveRef(this);
        TbNpcData.ResolveRef(this);
        TbClothShopData.ResolveRef(this);
        TbPropertyData.ResolveRef(this);
        TbUIPageData.ResolveRef(this);
        TbCharacterData.ResolveRef(this);
        TbSuperMarketShopData.ResolveRef(this);
        TbGameSceneData.ResolveRef(this);
        TbWordMapSceneData.ResolveRef(this);
        TbFruitShopData.ResolveRef(this);
        TbSexToShopData.ResolveRef(this);
        TbFishShopData.ResolveRef(this);
    }
}

}

