
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 角色属性配置表
/// </summary>
public partial class TbCharacterPropData
{
    private readonly System.Collections.Generic.Dictionary<CharacterPropType, CharacterPropData> _dataMap;
    private readonly System.Collections.Generic.List<CharacterPropData> _dataList;
    
    public TbCharacterPropData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<CharacterPropType, CharacterPropData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<CharacterPropData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            CharacterPropData _v;
            _v = global::XFramework.CharacterPropData.DeserializeCharacterPropData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Property, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<CharacterPropType, CharacterPropData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterPropData> DataList => _dataList;

    public CharacterPropData GetOrDefault(CharacterPropType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterPropData Get(CharacterPropType key) => _dataMap[key];
    public CharacterPropData this[CharacterPropType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

