
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 角色场景配置表
/// </summary>
public partial class TbCharacterShowRuleData
{
    private readonly System.Collections.Generic.Dictionary<long, CharacterShowRuleData> _dataMap;
    private readonly System.Collections.Generic.List<CharacterShowRuleData> _dataList;
    
    public TbCharacterShowRuleData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, CharacterShowRuleData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<CharacterShowRuleData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            CharacterShowRuleData _v;
            _v = global::XFramework.CharacterShowRuleData.DeserializeCharacterShowRuleData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, CharacterShowRuleData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterShowRuleData> DataList => _dataList;

    public CharacterShowRuleData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterShowRuleData Get(long key) => _dataMap[key];
    public CharacterShowRuleData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

