
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 角色配置表
/// </summary>
public partial class TbCharacterData
{
    private readonly System.Collections.Generic.Dictionary<long, CharacterData> _dataMap;
    private readonly System.Collections.Generic.List<CharacterData> _dataList;
    
    public TbCharacterData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, CharacterData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<CharacterData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            CharacterData _v;
            _v = global::XFramework.CharacterData.DeserializeCharacterData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, CharacterData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterData> DataList => _dataList;

    public CharacterData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterData Get(long key) => _dataMap[key];
    public CharacterData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

