
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 布料商店配置表
/// </summary>
public partial class TbClothShopData
{
    private readonly System.Collections.Generic.Dictionary<long, ClothShopData> _dataMap;
    private readonly System.Collections.Generic.List<ClothShopData> _dataList;
    
    public TbClothShopData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ClothShopData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ClothShopData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ClothShopData _v;
            _v = global::XFramework.ClothShopData.DeserializeClothShopData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ClothShopData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ClothShopData> DataList => _dataList;

    public ClothShopData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ClothShopData Get(long key) => _dataMap[key];
    public ClothShopData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

