
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 服装配件定义表
/// </summary>
public partial class TbClothingAccessoriesData
{
    private readonly System.Collections.Generic.Dictionary<long, ClothingAccessoriesData> _dataMap;
    private readonly System.Collections.Generic.List<ClothingAccessoriesData> _dataList;
    
    public TbClothingAccessoriesData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ClothingAccessoriesData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ClothingAccessoriesData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ClothingAccessoriesData _v;
            _v = global::XFramework.ClothingAccessoriesData.DeserializeClothingAccessoriesData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ClothingAccessoriesData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ClothingAccessoriesData> DataList => _dataList;

    public ClothingAccessoriesData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ClothingAccessoriesData Get(long key) => _dataMap[key];
    public ClothingAccessoriesData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

