
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbConsumption : Luban.BeanBase
{
    public TbConsumption(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Count = (int)_obj.GetValue("Count");
    }

    public static TbConsumption DeserializeTbConsumption(JToken _buf)
    {
        return new TbConsumption(_buf);
    }

    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;


    public const int __ID__ = 1708854317;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

