
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 消耗品道具配置表
/// </summary>
public partial class TbConsumablesItemData
{
    private readonly System.Collections.Generic.Dictionary<long, ConsumablesItemData> _dataMap;
    private readonly System.Collections.Generic.List<ConsumablesItemData> _dataList;
    
    public TbConsumablesItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ConsumablesItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ConsumablesItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ConsumablesItemData _v;
            _v = global::XFramework.ConsumablesItemData.DeserializeConsumablesItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ConsumablesItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ConsumablesItemData> DataList => _dataList;

    public ConsumablesItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ConsumablesItemData Get(long key) => _dataMap[key];
    public ConsumablesItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

