
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 游戏对话配置数据
/// </summary>
public partial class TbDialogueData
{
    private readonly System.Collections.Generic.Dictionary<long, DialogueData> _dataMap;
    private readonly System.Collections.Generic.List<DialogueData> _dataList;
    
    public TbDialogueData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, DialogueData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DialogueData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DialogueData _v;
            _v = global::XFramework.DialogueData.DeserializeDialogueData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, DialogueData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DialogueData> DataList => _dataList;

    public DialogueData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DialogueData Get(long key) => _dataMap[key];
    public DialogueData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

