
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 娃娃机配置
/// </summary>
public partial class TbDollCatalogData
{
    private readonly System.Collections.Generic.Dictionary<long, DollCatalogData> _dataMap;
    private readonly System.Collections.Generic.List<DollCatalogData> _dataList;
    
    public TbDollCatalogData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, DollCatalogData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DollCatalogData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DollCatalogData _v;
            _v = global::XFramework.DollCatalogData.DeserializeDollCatalogData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, DollCatalogData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DollCatalogData> DataList => _dataList;

    public DollCatalogData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DollCatalogData Get(long key) => _dataMap[key];
    public DollCatalogData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

