
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 展会信息表
/// </summary>
public partial class TbExhibitionInfoData
{
    private readonly System.Collections.Generic.Dictionary<long, ExhibitionInfoData> _dataMap;
    private readonly System.Collections.Generic.List<ExhibitionInfoData> _dataList;
    
    public TbExhibitionInfoData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ExhibitionInfoData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ExhibitionInfoData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ExhibitionInfoData _v;
            _v = global::XFramework.ExhibitionInfoData.DeserializeExhibitionInfoData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ExhibitionInfoData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ExhibitionInfoData> DataList => _dataList;

    public ExhibitionInfoData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ExhibitionInfoData Get(long key) => _dataMap[key];
    public ExhibitionInfoData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

