
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 钓鱼商店
/// </summary>
public partial class TbFishShopData
{
    private readonly System.Collections.Generic.Dictionary<long, FishShopData> _dataMap;
    private readonly System.Collections.Generic.List<FishShopData> _dataList;
    
    public TbFishShopData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, FishShopData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<FishShopData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            FishShopData _v;
            _v = global::XFramework.FishShopData.DeserializeFishShopData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, FishShopData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<FishShopData> DataList => _dataList;

    public FishShopData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FishShopData Get(long key) => _dataMap[key];
    public FishShopData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

