
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 礼物道具配置表
/// </summary>
public partial class TbGiftItemData
{
    private readonly System.Collections.Generic.Dictionary<long, GiftItemData> _dataMap;
    private readonly System.Collections.Generic.List<GiftItemData> _dataList;
    
    public TbGiftItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, GiftItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<GiftItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            GiftItemData _v;
            _v = global::XFramework.GiftItemData.DeserializeGiftItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, GiftItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GiftItemData> DataList => _dataList;

    public GiftItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GiftItemData Get(long key) => _dataMap[key];
    public GiftItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

