
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 材料道具配置表
/// </summary>
public partial class TbItemData
{
    private readonly System.Collections.Generic.Dictionary<long, ItemData> _dataMap;
    private readonly System.Collections.Generic.List<ItemData> _dataList;
    
    public TbItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, ItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ItemData _v;
            _v = global::XFramework.ItemData.DeserializeItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, ItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ItemData> DataList => _dataList;

    public ItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemData Get(long key) => _dataMap[key];
    public ItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

