
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbItem : Luban.BeanBase
{
    public TbItem(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        IconName = (string)_obj.GetValue("IconName");
        Remark = (string)_obj.GetValue("Remark");
        NameKey = (string)_obj.GetValue("NameKey");
        DescKey = (string)_obj.GetValue("DescKey");
        ItemType = (ItemType)(int)_obj.GetValue("ItemType");
        MaxNumber = (int)_obj.GetValue("MaxNumber");
        Quality = (ItemQuality)(int)_obj.GetValue("Quality");
    }

    public static TbItem DeserializeTbItem(JToken _buf)
    {
        return new TbItem(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 图标名称
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名称多语言
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 描述多语言
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly ItemType ItemType;
    /// <summary>
    /// 堆叠上限
    /// </summary>
    public readonly int MaxNumber;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly ItemQuality Quality;


    public const int __ID__ = -1797324095;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "IconName:" + IconName + ","
        + "Remark:" + Remark + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "ItemType:" + ItemType + ","
        + "MaxNumber:" + MaxNumber + ","
        + "Quality:" + Quality + ","
        + "}";
    }
}
}

