
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 材料道具配置表
/// </summary>
public partial class TbMaterialItemData
{
    private readonly System.Collections.Generic.Dictionary<long, MaterialItemData> _dataMap;
    private readonly System.Collections.Generic.List<MaterialItemData> _dataList;
    
    public TbMaterialItemData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, MaterialItemData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<MaterialItemData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            MaterialItemData _v;
            _v = global::XFramework.MaterialItemData.DeserializeMaterialItemData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, MaterialItemData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<MaterialItemData> DataList => _dataList;

    public MaterialItemData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MaterialItemData Get(long key) => _dataMap[key];
    public MaterialItemData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

