
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// NPC随机表
/// </summary>
public partial class TbNpcSpawnRuleData
{
    private readonly System.Collections.Generic.Dictionary<long, NpcSpawnRuleData> _dataMap;
    private readonly System.Collections.Generic.List<NpcSpawnRuleData> _dataList;
    
    public TbNpcSpawnRuleData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, NpcSpawnRuleData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<NpcSpawnRuleData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            NpcSpawnRuleData _v;
            _v = global::XFramework.NpcSpawnRuleData.DeserializeNpcSpawnRuleData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, NpcSpawnRuleData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<NpcSpawnRuleData> DataList => _dataList;

    public NpcSpawnRuleData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NpcSpawnRuleData Get(long key) => _dataMap[key];
    public NpcSpawnRuleData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

