
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// NPC配置表
/// </summary>
public partial class TbNpcData
{
    private readonly System.Collections.Generic.Dictionary<long, NpcData> _dataMap;
    private readonly System.Collections.Generic.List<NpcData> _dataList;
    
    public TbNpcData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, NpcData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<NpcData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            NpcData _v;
            _v = global::XFramework.NpcData.DeserializeNpcData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, NpcData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<NpcData> DataList => _dataList;

    public NpcData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NpcData Get(long key) => _dataMap[key];
    public NpcData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

