
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 场景随机出厂时刻表
/// </summary>
public partial class TbNpcSpawnGroupData
{
    private readonly System.Collections.Generic.Dictionary<long, NpcSpawnGroupData> _dataMap;
    private readonly System.Collections.Generic.List<NpcSpawnGroupData> _dataList;
    
    public TbNpcSpawnGroupData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, NpcSpawnGroupData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<NpcSpawnGroupData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            NpcSpawnGroupData _v;
            _v = global::XFramework.NpcSpawnGroupData.DeserializeNpcSpawnGroupData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, NpcSpawnGroupData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<NpcSpawnGroupData> DataList => _dataList;

    public NpcSpawnGroupData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NpcSpawnGroupData Get(long key) => _dataMap[key];
    public NpcSpawnGroupData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

