
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 配件板子定义表
/// </summary>
public partial class TbPcbSlotData
{
    private readonly System.Collections.Generic.Dictionary<long, PcbSlotData> _dataMap;
    private readonly System.Collections.Generic.List<PcbSlotData> _dataList;
    
    public TbPcbSlotData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, PcbSlotData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PcbSlotData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PcbSlotData _v;
            _v = global::XFramework.PcbSlotData.DeserializePcbSlotData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, PcbSlotData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PcbSlotData> DataList => _dataList;

    public PcbSlotData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PcbSlotData Get(long key) => _dataMap[key];
    public PcbSlotData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

