
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 展会人气表
/// </summary>
public partial class TbPopularityData
{
    private readonly System.Collections.Generic.Dictionary<long, PopularityData> _dataMap;
    private readonly System.Collections.Generic.List<PopularityData> _dataList;
    
    public TbPopularityData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, PopularityData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PopularityData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PopularityData _v;
            _v = global::XFramework.PopularityData.DeserializePopularityData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, PopularityData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PopularityData> DataList => _dataList;

    public PopularityData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PopularityData Get(long key) => _dataMap[key];
    public PopularityData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

