
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbPopularityData : Luban.BeanBase
{
    public TbPopularityData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Rank = (int)_obj.GetValue("Rank");
        Name = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("Name"));
        Value = (int)_obj.GetValue("Value");
    }

    public static TbPopularityData DeserializeTbPopularityData(JToken _buf)
    {
        return new TbPopularityData(_buf);
    }

    public readonly int Rank;
    public readonly TbLocalzationKeyData Name;
    public readonly int Value;


    public const int __ID__ = -762178899;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Rank:" + Rank + ","
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

