
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 任务配置表
/// </summary>
public partial class TbQuestData
{
    private readonly System.Collections.Generic.Dictionary<long, QuestDataConfig> _dataMap;
    private readonly System.Collections.Generic.List<QuestDataConfig> _dataList;
    
    public TbQuestData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, QuestDataConfig>(_buf.Count);
        _dataList = new System.Collections.Generic.List<QuestDataConfig>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            QuestDataConfig _v;
            _v = global::XFramework.QuestDataConfig.DeserializeQuestDataConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, QuestDataConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestDataConfig> DataList => _dataList;

    public QuestDataConfig GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestDataConfig Get(long key) => _dataMap[key];
    public QuestDataConfig this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

