
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 任务/剧情状态条件表
/// </summary>
public partial class TbQuestStoryCondData
{
    private readonly System.Collections.Generic.Dictionary<long, QuestStoryCondData> _dataMap;
    private readonly System.Collections.Generic.List<QuestStoryCondData> _dataList;
    
    public TbQuestStoryCondData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, QuestStoryCondData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<QuestStoryCondData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            QuestStoryCondData _v;
            _v = global::XFramework.QuestStoryCondData.DeserializeQuestStoryCondData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, QuestStoryCondData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestStoryCondData> DataList => _dataList;

    public QuestStoryCondData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestStoryCondData Get(long key) => _dataMap[key];
    public QuestStoryCondData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

