
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 任务目标配置表
/// </summary>
public partial class TbQuestObjData
{
    private readonly System.Collections.Generic.Dictionary<long, QuestObjConfig> _dataMap;
    private readonly System.Collections.Generic.List<QuestObjConfig> _dataList;
    
    public TbQuestObjData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, QuestObjConfig>(_buf.Count);
        _dataList = new System.Collections.Generic.List<QuestObjConfig>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            QuestObjConfig _v;
            _v = global::XFramework.QuestObjConfig.DeserializeQuestObjConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, QuestObjConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestObjConfig> DataList => _dataList;

    public QuestObjConfig GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestObjConfig Get(long key) => _dataMap[key];
    public QuestObjConfig this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

