
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 任务奖励展示配置表
/// </summary>
public partial class TbQuestRewardData
{
    private readonly System.Collections.Generic.Dictionary<string, QuestRewardData> _dataMap;
    private readonly System.Collections.Generic.List<QuestRewardData> _dataList;
    
    public TbQuestRewardData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, QuestRewardData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<QuestRewardData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            QuestRewardData _v;
            _v = global::XFramework.QuestRewardData.DeserializeQuestRewardData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, QuestRewardData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestRewardData> DataList => _dataList;

    public QuestRewardData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestRewardData Get(string key) => _dataMap[key];
    public QuestRewardData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

