
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 任务类别配置表
/// </summary>
public partial class TbQuestCategoryData
{
    private readonly System.Collections.Generic.Dictionary<long, QuestCategoryData> _dataMap;
    private readonly System.Collections.Generic.List<QuestCategoryData> _dataList;
    
    public TbQuestCategoryData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, QuestCategoryData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<QuestCategoryData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            QuestCategoryData _v;
            _v = global::XFramework.QuestCategoryData.DeserializeQuestCategoryData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, QuestCategoryData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestCategoryData> DataList => _dataList;

    public QuestCategoryData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestCategoryData Get(long key) => _dataMap[key];
    public QuestCategoryData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

