
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 赛车小游戏赛道配置表
/// </summary>
public partial class TbRacingTrackData
{
    private readonly System.Collections.Generic.Dictionary<long, RacingTrackData> _dataMap;
    private readonly System.Collections.Generic.List<RacingTrackData> _dataList;
    
    public TbRacingTrackData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, RacingTrackData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<RacingTrackData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            RacingTrackData _v;
            _v = global::XFramework.RacingTrackData.DeserializeRacingTrackData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, RacingTrackData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RacingTrackData> DataList => _dataList;

    public RacingTrackData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RacingTrackData Get(long key) => _dataMap[key];
    public RacingTrackData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

