
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbRewardCharacterPropData : Luban.BeanBase
{
    public TbRewardCharacterPropData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        CharacterPropType = (CharacterPropType)(int)_obj.GetValue("CharacterPropType");
        CharacterID = (long)_obj.GetValue("CharacterID");
        Value = (int)_obj.GetValue("Value");
    }

    public static TbRewardCharacterPropData DeserializeTbRewardCharacterPropData(JToken _buf)
    {
        return new TbRewardCharacterPropData(_buf);
    }

    public readonly CharacterPropType CharacterPropType;
    public readonly long CharacterID;
    public readonly int Value;


    public const int __ID__ = 251897369;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CharacterPropType:" + CharacterPropType + ","
        + "CharacterID:" + CharacterID + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

