
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbRewardItemData : Luban.BeanBase
{
    public TbRewardItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Count = (int)_obj.GetValue("Count");
    }

    public static TbRewardItemData DeserializeTbRewardItemData(JToken _buf)
    {
        return new TbRewardItemData(_buf);
    }

    public readonly long ItemID;
    public readonly int Count;


    public const int __ID__ = -666535974;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

