
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 奖励表
/// </summary>
public partial class TbRewardData
{
    private readonly System.Collections.Generic.Dictionary<long, RewardData> _dataMap;
    private readonly System.Collections.Generic.List<RewardData> _dataList;
    
    public TbRewardData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, RewardData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<RewardData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            RewardData _v;
            _v = global::XFramework.RewardData.DeserializeRewardData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, RewardData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RewardData> DataList => _dataList;

    public RewardData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RewardData Get(long key) => _dataMap[key];
    public RewardData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

