
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbRewardPropData : Luban.BeanBase
{
    public TbRewardPropData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        PropType = (PropertyType)(int)_obj.GetValue("PropType");
        Value = (int)_obj.GetValue("Value");
    }

    public static TbRewardPropData DeserializeTbRewardPropData(JToken _buf)
    {
        return new TbRewardPropData(_buf);
    }

    public readonly PropertyType PropType;
    public readonly int Value;


    public const int __ID__ = 1457256490;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PropType:" + PropType + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

