
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 情趣用品店配置表
/// </summary>
public partial class TbSexToShopData
{
    private readonly System.Collections.Generic.Dictionary<long, SexToShopData> _dataMap;
    private readonly System.Collections.Generic.List<SexToShopData> _dataList;
    
    public TbSexToShopData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, SexToShopData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<SexToShopData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            SexToShopData _v;
            _v = global::XFramework.SexToShopData.DeserializeSexToShopData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, SexToShopData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SexToShopData> DataList => _dataList;

    public SexToShopData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SexToShopData Get(long key) => _dataMap[key];
    public SexToShopData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

