
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 服装喷漆小游戏配置
/// </summary>
public partial class TbSprayPaintGameData
{
    private readonly System.Collections.Generic.Dictionary<long, SprayPaintGameData> _dataMap;
    private readonly System.Collections.Generic.List<SprayPaintGameData> _dataList;
    
    public TbSprayPaintGameData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, SprayPaintGameData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<SprayPaintGameData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            SprayPaintGameData _v;
            _v = global::XFramework.SprayPaintGameData.DeserializeSprayPaintGameData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ClothingID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, SprayPaintGameData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SprayPaintGameData> DataList => _dataList;

    public SprayPaintGameData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SprayPaintGameData Get(long key) => _dataMap[key];
    public SprayPaintGameData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

