
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 引导步骤表
/// </summary>
public partial class TbTutorialStepData
{
    private readonly System.Collections.Generic.Dictionary<long, TutorialStepData> _dataMap;
    private readonly System.Collections.Generic.List<TutorialStepData> _dataList;
    
    public TbTutorialStepData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, TutorialStepData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<TutorialStepData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            TutorialStepData _v;
            _v = global::XFramework.TutorialStepData.DeserializeTutorialStepData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, TutorialStepData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TutorialStepData> DataList => _dataList;

    public TutorialStepData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TutorialStepData Get(long key) => _dataMap[key];
    public TutorialStepData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

