
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 引导流程表
/// </summary>
public partial class TbTutorialData
{
    private readonly System.Collections.Generic.Dictionary<long, TutorialData> _dataMap;
    private readonly System.Collections.Generic.List<TutorialData> _dataList;
    
    public TbTutorialData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<long, TutorialData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<TutorialData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            TutorialData _v;
            _v = global::XFramework.TutorialData.DeserializeTutorialData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<long, TutorialData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TutorialData> DataList => _dataList;

    public TutorialData GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TutorialData Get(long key) => _dataMap[key];
    public TutorialData this[long key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

