
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbUlockDateData : Luban.BeanBase
{
    public TbUlockDateData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        WeekFlag = (ShowRuleWeekType)(int)_obj.GetValue("WeekFlag");
        TimeFlag = (ShowRuleTimeType)(int)_obj.GetValue("TimeFlag");
    }

    public static TbUlockDateData DeserializeTbUlockDateData(JToken _buf)
    {
        return new TbUlockDateData(_buf);
    }

    /// <summary>
    /// 周几
    /// </summary>
    public readonly ShowRuleWeekType WeekFlag;
    /// <summary>
    /// 时间段
    /// </summary>
    public readonly ShowRuleTimeType TimeFlag;


    public const int __ID__ = -768487478;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "WeekFlag:" + WeekFlag + ","
        + "TimeFlag:" + TimeFlag + ","
        + "}";
    }
}
}

