
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbUlockCharacterData : Luban.BeanBase
{
    public TbUlockCharacterData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        CharacterID = (long)_obj.GetValue("CharacterID");
        CharacterType = (CharacterPropType)(int)_obj.GetValue("CharacterType");
        Value = (int)_obj.GetValue("Value");
    }

    public static TbUlockCharacterData DeserializeTbUlockCharacterData(JToken _buf)
    {
        return new TbUlockCharacterData(_buf);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public readonly long CharacterID;
    /// <summary>
    /// 角色属性类型
    /// </summary>
    public readonly CharacterPropType CharacterType;
    /// <summary>
    /// 需求值
    /// </summary>
    public readonly int Value;


    public const int __ID__ = -1021205919;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CharacterID:" + CharacterID + ","
        + "CharacterType:" + CharacterType + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

