
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbUlocakItemData : Luban.BeanBase
{
    public TbUlocakItemData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (long)_obj.GetValue("ItemID");
        Value = (int)_obj.GetValue("Value");
    }

    public static TbUlocakItemData DeserializeTbUlocakItemData(JToken _buf)
    {
        return new TbUlocakItemData(_buf);
    }

    /// <summary>
    /// 需求的物品ID
    /// </summary>
    public readonly long ItemID;
    /// <summary>
    /// 需求的物品数量
    /// </summary>
    public readonly int Value;


    public const int __ID__ = -995179840;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

