
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialRepeatType
    {
        /// <summary>
        /// 记进存档，读别的档还会再播
        /// </summary>
        Once = 0,
        /// <summary>
        /// 记进全局文件，所有存档只播一次
        /// </summary>
        OnceGlobal = 1,
        /// <summary>
        /// 不记录完成，满足触发就播，调试用
        /// </summary>
        Always = 2,
    }

} 

