
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialTriggerType
    {
        /// <summary>
        /// 只由代码主动调用 TutorialManager.StartTutorial，TriggerParam 不填
        /// </summary>
        Manual = 0,
        /// <summary>
        /// TriggerParam = 小场景ID(SceneData.SceneID)
        /// </summary>
        EnterScene = 1,
        /// <summary>
        /// TriggerParam = UI界面的PageID
        /// </summary>
        OpenUI = 2,
        /// <summary>
        /// TriggerParam = 剧情ID
        /// </summary>
        DramaFinish = 3,
        /// <summary>
        /// TriggerParam = 事件名，业务调 TutorialManager.TriggerEvent
        /// </summary>
        Event = 4,
    }

} 

