
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialHandType
    {
        /// <summary>
        /// 不显示指引图标
        /// </summary>
        None = 0,
        /// <summary>
        /// 手指图标，带循环点击动画
        /// </summary>
        Finger = 1,
        /// <summary>
        /// 箭头图标，按 HandRotation 旋转
        /// </summary>
        Arrow = 2,
    }

} 

