
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialFinishType
    {
        /// <summary>
        /// 点中本步目标节点才过，FinishParam 不填
        /// </summary>
        ClickTarget = 0,
        /// <summary>
        /// 点屏幕任意位置过场，纯文字提示用
        /// </summary>
        AnyClick = 1,
        /// <summary>
        /// FinishParam = 要等待打开的界面PageID
        /// </summary>
        UIOpen = 2,
        /// <summary>
        /// FinishParam = 事件名，业务调 TutorialManager.TriggerEvent
        /// </summary>
        Event = 3,
        /// <summary>
        /// FinishParam = 等待秒数
        /// </summary>
        Delay = 4,
    }

} 

