
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialTargetType
    {
        /// <summary>
        /// 不挖洞，只显示全屏遮罩和提示文字
        /// </summary>
        None = 0,
        /// <summary>
        /// TargetPageID + TargetPath 定位，路径写法同 AutoBind
        /// </summary>
        UIPath = 1,
        /// <summary>
        /// AnchorKey 定位，给动态生成的节点用（列表项等）
        /// </summary>
        Anchor = 2,
    }

} 

