
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TutorialStepData : Luban.BeanBase
{
    public TutorialStepData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        TutorialID = (long)_obj.GetValue("TutorialID");
        StepIndex = (int)_obj.GetValue("StepIndex");
        TargetType = (TutorialTargetType)(int)_obj.GetValue("TargetType");
        TargetPageID = (string)_obj.GetValue("TargetPageID");
        TargetPath = (string)_obj.GetValue("TargetPath");
        AnchorKey = (string)_obj.GetValue("AnchorKey");
        MaskFitType = (TutorialMaskFitType)(int)_obj.GetValue("MaskFitType");
        MaskSpriteName = (string)_obj.GetValue("MaskSpriteName");
        MaskSize = global::XFramework.vector2.Deserializevector2(_obj.GetValue("MaskSize"));
        MaskOffset = global::XFramework.vector2.Deserializevector2(_obj.GetValue("MaskOffset"));
        MaskPadding = global::XFramework.vector4.Deserializevector4(_obj.GetValue("MaskPadding"));
        TipTextKey = (string)_obj.GetValue("TipTextKey");
        TipPosType = (TutorialTipPos)(int)_obj.GetValue("TipPosType");
        HandType = (TutorialHandType)(int)_obj.GetValue("HandType");
        HandRotation = (float)_obj.GetValue("HandRotation");
        HandPosition = global::XFramework.vector2.Deserializevector2(_obj.GetValue("HandPosition"));
        FinishType = (TutorialFinishType)(int)_obj.GetValue("FinishType");
        FinishParam = (string)_obj.GetValue("FinishParam");
        ClickThrough = (bool)_obj.GetValue("ClickThrough");
        Description = (string)_obj.GetValue("Description");
    }

    public static TutorialStepData DeserializeTutorialStepData(JToken _buf)
    {
        return new TutorialStepData(_buf);
    }

    /// <summary>
    /// 步骤ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 所属引导ID
    /// </summary>
    public readonly long TutorialID;
    /// <summary>
    /// 组内顺序(从1开始)
    /// </summary>
    public readonly int StepIndex;
    /// <summary>
    /// 目标定位方式
    /// </summary>
    public readonly TutorialTargetType TargetType;
    /// <summary>
    /// 目标界面PageID(UIPath用)
    /// </summary>
    public readonly string TargetPageID;
    /// <summary>
    /// 目标节点路径(UIPath用,写法同AutoBind)
    /// </summary>
    public readonly string TargetPath;
    /// <summary>
    /// 运行时锚点Key(Anchor用)
    /// </summary>
    public readonly string AnchorKey;
    /// <summary>
    /// 洞的适配方式
    /// </summary>
    public readonly TutorialMaskFitType MaskFitType;
    /// <summary>
    /// 洞的Sprite资源名(空=默认方形九宫格)
    /// </summary>
    public readonly string MaskSpriteName;
    /// <summary>
    /// 洞的自定义尺寸(Custom用,宽,高)
    /// </summary>
    public readonly vector2 MaskSize;
    /// <summary>
    /// 洞相对目标的偏移(x,y)
    /// </summary>
    public readonly vector2 MaskOffset;
    /// <summary>
    /// 洞的四边扩边(左,右,上,下)
    /// </summary>
    public readonly vector4 MaskPadding;
    /// <summary>
    /// 提示文本本地化Key(空=不显示气泡)
    /// </summary>
    public readonly string TipTextKey;
    /// <summary>
    /// 气泡位置
    /// </summary>
    public readonly TutorialTipPos TipPosType;
    /// <summary>
    /// 指引图标
    /// </summary>
    public readonly TutorialHandType HandType;
    /// <summary>
    /// 指引图标旋转角度
    /// </summary>
    public readonly float HandRotation;
    /// <summary>
    /// 指引图标的位置(x,y),屏幕中心为原点,编辑器里摆好直接抄Inspector的Pos X/Y
    /// </summary>
    public readonly vector2 HandPosition;
    /// <summary>
    /// 本步完成条件
    /// </summary>
    public readonly TutorialFinishType FinishType;
    /// <summary>
    /// 完成条件参数(PageID/事件名/秒数)
    /// </summary>
    public readonly string FinishParam;
    /// <summary>
    /// 洞内点击是否透传给目标
    /// </summary>
    public readonly bool ClickThrough;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -855131596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "TutorialID:" + TutorialID + ","
        + "StepIndex:" + StepIndex + ","
        + "TargetType:" + TargetType + ","
        + "TargetPageID:" + TargetPageID + ","
        + "TargetPath:" + TargetPath + ","
        + "AnchorKey:" + AnchorKey + ","
        + "MaskFitType:" + MaskFitType + ","
        + "MaskSpriteName:" + MaskSpriteName + ","
        + "MaskSize:" + MaskSize + ","
        + "MaskOffset:" + MaskOffset + ","
        + "MaskPadding:" + MaskPadding + ","
        + "TipTextKey:" + TipTextKey + ","
        + "TipPosType:" + TipPosType + ","
        + "HandType:" + HandType + ","
        + "HandRotation:" + HandRotation + ","
        + "HandPosition:" + HandPosition + ","
        + "FinishType:" + FinishType + ","
        + "FinishParam:" + FinishParam + ","
        + "ClickThrough:" + ClickThrough + ","
        + "Description:" + Description + ","
        + "}";
    }
}
}

