
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialMaskFitType
    {
        /// <summary>
        /// 洞的大小跟着目标RectTransform走，再套 MaskPadding 扩边，方形按钮用这个
        /// </summary>
        FitTarget = 0,
        /// <summary>
        /// 洞只取目标的位置，大小用 MaskSize、偏移用 MaskOffset，人物立绘这类异形洞用这个
        /// </summary>
        Custom = 1,
    }

} 

