
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum TutorialTipPos
    {
        /// <summary>
        /// 按目标在屏幕上的位置自动挑一侧，避免出屏
        /// </summary>
        Auto = 0,
        /// <summary>
        /// 气泡固定在洞的上方
        /// </summary>
        Up = 1,
        /// <summary>
        /// 气泡固定在洞的下方
        /// </summary>
        Down = 2,
        /// <summary>
        /// 气泡固定在洞的左侧
        /// </summary>
        Left = 3,
        /// <summary>
        /// 气泡固定在洞的右侧
        /// </summary>
        Right = 4,
    }

} 

