
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TutorialData : Luban.BeanBase
{
    public TutorialData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        TriggerType = (TutorialTriggerType)(int)_obj.GetValue("TriggerType");
        TriggerParam = (string)_obj.GetValue("TriggerParam");
        UnlockConditionID = (long)_obj.GetValue("UnlockConditionID");
        RepeatType = (TutorialRepeatType)(int)_obj.GetValue("RepeatType");
        Priority = (int)_obj.GetValue("Priority");
        Description = (string)_obj.GetValue("Description");
    }

    public static TutorialData DeserializeTutorialData(JToken _buf)
    {
        return new TutorialData(_buf);
    }

    /// <summary>
    /// 引导ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 触发方式
    /// </summary>
    public readonly TutorialTriggerType TriggerType;
    /// <summary>
    /// 触发参数(小场景ID/界面PageID/剧情ID/事件名)
    /// </summary>
    public readonly string TriggerParam;
    /// <summary>
    /// 额外解锁条件ID(解锁条件表,0=无)
    /// </summary>
    public readonly long UnlockConditionID;
    /// <summary>
    /// 重复规则
    /// </summary>
    public readonly TutorialRepeatType RepeatType;
    /// <summary>
    /// 优先级(大的先播)
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 772801608;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "TriggerType:" + TriggerType + ","
        + "TriggerParam:" + TriggerParam + ","
        + "UnlockConditionID:" + UnlockConditionID + ","
        + "RepeatType:" + RepeatType + ","
        + "Priority:" + Priority + ","
        + "Description:" + Description + ","
        + "}";
    }
}
}

