
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    [System.Flags]
    public enum UnlockConditionsType
    {
        /// <summary>
        /// 没有解锁条件
        /// </summary>
        None = 1,
        /// <summary>
        /// 玩家属性
        /// </summary>
        Prop = 2,
        /// <summary>
        /// 玩家物品
        /// </summary>
        Item = 4,
        /// <summary>
        /// 角色
        /// </summary>
        Character = 8,
        /// <summary>
        /// 时间
        /// </summary>
        Date = 16,
    }

} 

