
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class WordMapSceneData : Luban.BeanBase
{
    public WordMapSceneData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ID = (long)_obj.GetValue("ID");
        Remark = (string)_obj.GetValue("Remark");
        SceneName = global::XFramework.TbLocalzationKeyData.DeserializeTbLocalzationKeyData(_obj.GetValue("SceneName"));
        { var __json0 = _obj.GetValue("SubScenes"); SubScenes = new System.Collections.Generic.List<long>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { long __v0;  __v0 = (long)__e0;  SubScenes.Add(__v0); }   }
    }

    public static WordMapSceneData DeserializeWordMapSceneData(JToken _buf)
    {
        return new WordMapSceneData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly long ID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly TbLocalzationKeyData SceneName;
    /// <summary>
    /// 子场景(ID)
    /// </summary>
    public readonly System.Collections.Generic.List<long> SubScenes;


    public const int __ID__ = -664913756;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SceneName?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Remark:" + Remark + ","
        + "SceneName:" + SceneName + ","
        + "SubScenes:" + Luban.StringUtil.CollectionToString(SubScenes) + ","
        + "}";
    }
}
}

