// <auto-generated />
using UnityEngine;

public partial class ExhibitionGameSlot
{
    private MerchandiseRuntimeSlot merchandiseRuntimeSlot;
    private UnityEngine.RectTransform flySlot;
    private UnityEngine.RectTransform noneRect;

    private void InitAutoBind()
    {
        merchandiseRuntimeSlot = Get<MerchandiseRuntimeSlot>("MerchandiseRuntimeSlot");
        flySlot = Get<UnityEngine.RectTransform>("FlySlot");
        noneRect = Get<UnityEngine.RectTransform>("NoneRect");

    }
}
