#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace XFramework
{
    /// <summary>
    /// 从 Luban 导出的 tbuipagedata.json 生成 UI 界面 ID 常量类。
    /// 避免代码里手写 "CommonUI" 这类字符串 —— 拼错编译期发现不了，只能在运行时才暴露。
    /// </summary>
    public static class UIKeysGenerator
    {
        private const string SourceJsonPath =
            "Assets/AddressableAssets/Remote/Configs/LubanJson/tbuipagedata.json";

        private const string OutputPath = "Assets/Scripts/XFramework/Base/UI/UIKeys.cs";
        private const string ClassName = "UIKeys";
        private const string NamespaceName = "XFramework";
        private const string IdFieldName = "PageID";
        private const string DescriptionFieldName = "Description";

        /// <summary>
        /// 读取 UI 配置表 Json 并生成 UIKeys.cs。
        /// </summary>
        /// <returns>生成成功返回 true。</returns>
        public static bool Generate()
        {
            if (!TryReadEntries(out var entries))
            {
                return false;
            }

            if (entries.Count == 0)
            {
                Debug.LogWarning($"[UIKeys] UI 配置表里没有任何记录: {SourceJsonPath}");
                return false;
            }

            string scriptContent = BuildScript(entries);
            string directory = Path.GetDirectoryName(OutputPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(OutputPath, scriptContent, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath);

            Debug.Log($"[UIKeys] 生成成功: {OutputPath}\n共 {entries.Count} 条 UI 界面 ID 常量。");
            return true;
        }

        private static bool TryReadEntries(out List<UIPageEntry> entries)
        {
            entries = new List<UIPageEntry>();

            if (!File.Exists(SourceJsonPath))
            {
                Debug.LogError($"[UIKeys] UI 配置表 Json 不存在: {SourceJsonPath}\n请先执行 gen_client.bat 导出配置。");
                return false;
            }

            JArray array;

            try
            {
                array = JArray.Parse(File.ReadAllText(SourceJsonPath));
            }
            catch (Exception e)
            {
                Debug.LogError($"[UIKeys] 解析 UI 配置表 Json 失败: {SourceJsonPath}\n{e.Message}");
                return false;
            }

            var seenIds = new HashSet<string>(StringComparer.Ordinal);

            foreach (JToken token in array)
            {
                if (token is not JObject item)
                {
                    continue;
                }

                string pageId = item[IdFieldName]?.ToString();

                if (string.IsNullOrWhiteSpace(pageId))
                {
                    Debug.LogError($"[UIKeys] 有记录的 {IdFieldName} 为空，请先补全 UIPageData 表后重新导出。");
                    return false;
                }

                // PageID 是 TbUIPageData 的字典键，重复会让 Luban 反序列化直接抛异常，
                // 这里提前拦下来，报错比生成一份错的常量类好。
                if (!seenIds.Add(pageId))
                {
                    Debug.LogError($"[UIKeys] {IdFieldName} 重复: {pageId}，请改成唯一值后重新导出。");
                    return false;
                }

                entries.Add(new UIPageEntry
                {
                    PageId = pageId,
                    Description = item[DescriptionFieldName]?.ToString()
                });
            }

            return true;
        }

        private static string BuildScript(List<UIPageEntry> entries)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此文件由 UIKeysGenerator 自动生成。");
            sb.AppendLine("//     请不要手动修改，重新生成会覆盖内容。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine($"namespace {NamespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {ClassName}");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            // 保持配置表顺序，生成结果和表格逐行对应，diff 更好读。
            foreach (UIPageEntry entry in entries)
            {
                string constName = MakeUniqueName(ToConstName(entry.PageId), usedNames);
                string summary = string.IsNullOrWhiteSpace(entry.Description)
                    ? entry.PageId
                    : $"{entry.Description} ({entry.PageId})";

                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {EscapeXmlDoc(summary)}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public const string {constName} = \"{EscapeString(entry.PageId)}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 把 PageID 转成合法的 C# 标识符，例如 Pop_Loading_UI -> PopLoadingUI。
        /// </summary>
        private static string ToConstName(string pageId)
        {
            StringBuilder sb = new StringBuilder();
            bool nextUpper = true;

            foreach (char c in pageId)
            {
                if (char.IsLetterOrDigit(c))
                {
                    // 标识符不能以数字开头。
                    if (sb.Length == 0 && char.IsDigit(c))
                    {
                        sb.Append('_');
                    }

                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            return sb.Length == 0 ? "Unnamed" : sb.ToString();
        }

        private static string MakeUniqueName(string baseName, HashSet<string> usedNames)
        {
            if (usedNames.Add(baseName))
            {
                return baseName;
            }

            int index = 2;

            while (!usedNames.Add(baseName + index))
            {
                index++;
            }

            return baseName + index;
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }

        private static string EscapeXmlDoc(string value)
        {
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        private class UIPageEntry
        {
            public string PageId;
            public string Description;
        }
    }
}

#endif
