// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class BottleSlot
{
    private UnityEngine.UI.Image icon;
    private UnityEngine.UI.Image mask;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("Icon");
        mask = Get<UnityEngine.UI.Image>("Mask");

    }
}
