// <auto-generated />
using UnityEngine;

public partial class MessageSlot
{
    private UnityEngine.Localization.Components.LocalizeStringEvent desc;
    private UnityEngine.RectTransform textureLayoutGroup;
    private UnityEngine.UI.VerticalLayoutGroup descLayoutGroup;
    private TMPro.TextMeshProUGUI commentValTex;
    private TMPro.TextMeshProUGUI shareValTex;
    private TMPro.TextMeshProUGUI heartValTex;

    private void InitAutoBind()
    {
        desc = Get<UnityEngine.Localization.Components.LocalizeStringEvent>("DescLayoutGroup/Desc");
        textureLayoutGroup = Get<UnityEngine.RectTransform>("TextureLayoutGroup");
        descLayoutGroup = Get<UnityEngine.UI.VerticalLayoutGroup>("DescLayoutGroup");
        commentValTex = Get<TMPro.TextMeshProUGUI>("DownTools/Group/Comment/CommentValTex");
        shareValTex = Get<TMPro.TextMeshProUGUI>("DownTools/Group/Share/ShareValTex");
        heartValTex = Get<TMPro.TextMeshProUGUI>("DownTools/Group/Heart/HeartValTex");

    }
}
