// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class SweingMachinePanel
{
    private UnityEngine.RectTransform mouseParent;
    private UnityEngine.RectTransform slotParent;
    private List<SewingMachineSlotParent> mouseParent2;

    private void InitAutoBind()
    {
        mouseParent = Get<UnityEngine.RectTransform>("MouseParent");
        slotParent = Get<UnityEngine.RectTransform>("SlotParent");
        mouseParent2 = Get<Transform>("MouseParent").GetComponentsInChildren<SewingMachineSlotParent>(true).Where(item => item.transform != Get<Transform>("MouseParent")).ToList();

    }
}
