<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\..\..\..\..\..\..\Library\InspectorBridgeSourceCodeMcp\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;Library\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
